"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process"),crypto=require("node:crypto"),Module=require("node:module");
const ROOT=path.resolve(__dirname,"../.."),AIR=process.env.HARDENED_FIXTURE_AIR_SDK,LAYA=process.env.HARDENED_FIXTURE_LAYA,FFDEC=process.env.HARDENED_FIXTURE_FFDEC;
const EVIDENCE_REVISION="676d8c2a9a80b171709e13c9fcad18230624fdb8",sha=bytes=>crypto.createHash("sha256").update(bytes).digest("hex");

test("one-argument Date admits exact Number epochs under retained AIR authority",{skip:!AIR||!LAYA||!FFDEC},t=>{
 const laya=fs.realpathSync(LAYA),fixture=path.join(laya,"tests/nativeFlashOracle/date-construction");
 const ancestor=cp.spawnSync("git",["merge-base","--is-ancestor",EVIDENCE_REVISION,"HEAD"],{cwd:laya,encoding:"utf8"});assert.equal(ancestor.status,0,ancestor.stderr||"Date epoch evidence is not retained");
 for(const [name,expected] of [
  ["DateEpochControlsProbe.as","0635aadb3528273f6909d02a4707d3326316fe6570864fba6bf88efda617118e"],
  ["epoch-scenario.json","cac9ff8cc1a5f794b063378beb3ac7221769e0c74cc8e883f16e39250b3a1d07"],
  ["native-air.json","5229dec95ee4b59602b67b9c3c121322aa6d84df39ac3b4a415adafa0eda19fd"],
  ["sdk-authority.json","0d0228cec7c0a8e4b8543397a79dff02bc3b09f2e0666a4736ce6e0e73186252"],
 ]){const object=cp.execFileSync("git",["show",`${EVIDENCE_REVISION}:tests/nativeFlashOracle/date-construction/${name}`],{cwd:laya});assert.equal(sha(object),expected,`Git object ${name}`);assert.equal(sha(fs.readFileSync(path.join(fixture,name))),expected,name);}
 const retained=JSON.parse(fs.readFileSync(path.join(fixture,"native-air.json"))),epoch=retained.captures.epoch;
 assert.equal(epoch.capture.runtime.version,"MAC 51,3,3,2");assert.equal(epoch.captureSha256,"301163bb86b69c22a05ee9c6fdac7600b891aa11859a4c0ae2927d71cd69d7a3");assert.equal(epoch.receiptSha256,"2e4911e97ab005a6640d506a3fcea52d435a94edd51037953c597d1ffc6a05e3");assert.equal(epoch.capture.state.observations.length,10);

 const temporary=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),"date-epoch-cli-")));t.after(()=>fs.rmSync(temporary,{recursive:true,force:true}));const source=path.join(temporary,"source"),profile=path.join(temporary,"profile");fs.mkdirSync(source);
 const sources={
  DateEpochCompiled:'package {public class DateEpochCompiled {public function exercise(value:Number):Array {var date:Date=new Date(value);var milliseconds:Number=date.valueOf();var getTime:Number=date.getTime();if(isNaN(milliseconds)) return ["NaN",isNaN(getTime),isNaN(date.time),date is Date,typeof milliseconds];return ["number",milliseconds,getTime,date.time,date is Date,typeof milliseconds];}}}',
  TimeManagerEpoch:'package {public class TimeManagerEpoch {private static const OFFSET:int=-480;public static function setTimezoneOffset(param1:Number):Date {var date:Date=new Date(param1);date.minutes-=OFFSET-date.timezoneOffset;return date;}public static function reSetTimezoneOffset(param1:Number):Date {var date:Date=new Date(param1);date.minutes+=OFFSET-date.timezoneOffset;return date;}public static function getDiffTime(param1:Number,param2:Number):Number {var first:Date=new Date(param1);var second:Date=new Date(param2);return param2-param1+(first.timezoneOffset-second.timezoneOffset)*60*1000;}public static function clone(date:Date):Date {return new Date(date.time);}}}',
 };
 for(const [name,text] of Object.entries(sources))fs.writeFileSync(path.join(source,name+".as"),text);
 const run=(command,args)=>{const result=cp.spawnSync(command,args,{cwd:ROOT,encoding:"utf8",timeout:180000});assert.equal(result.status,0,result.stdout+result.stderr);return result;};
 const makeProfile=()=>run("python3",["-B","tools/create-fixture-profile.py","--source",source,"--entry","DateEpochCompiled","--air-sdk",AIR,"--laya",laya,"--ffdec-jar",FFDEC,"--native-date","--output",profile]);makeProfile();
 const compile=(operation,name)=>run(process.execPath,["bin/as3-frontend",operation,source,path.join(temporary,name),"--source-census",path.join(profile,"census.json"),"--target-capabilities",path.join(laya,"docTool/architecture/authored-content-capabilities.json"),"--profile-lock",path.join(profile,"profile-lock.json")]);
 compile("transpile","output");const output=path.join(temporary,"output"),manifest=JSON.parse(fs.readFileSync(path.join(output,"manifest.json")));
 const code={};for(const [name,text] of Object.entries(sources)){const row=manifest.files.find(item=>item.sourcePath===name+".as");assert.ok(row&&row.typescriptPath,JSON.stringify(row));assert.equal(row.sourceSha256,sha(text));code[name]=fs.readFileSync(path.join(output,row.typescriptPath),"utf8");}
 assert.match(code.DateEpochCompiled,/new AS3Date\(value\)/);for(const expression of ["param1","param2"])assert.match(code.TimeManagerEpoch,new RegExp(`new AS3Date\\(${expression}\\)`));assert.match(code.TimeManagerEpoch,/new AS3Date\(__as3DateReceiver\(date\)\.time\)/);
 const packageInfo=JSON.parse(fs.readFileSync(path.join(output,"__as3_runtime/package.json"))),files=Object.keys(sources).map(name=>path.join(output,manifest.files.find(item=>item.sourcePath===name+".as").typescriptPath)),tsconfig=path.join(output,"strict-tsconfig.json");
 fs.writeFileSync(tsconfig,JSON.stringify({compilerOptions:{target:"ES2020",module:"CommonJS",moduleResolution:"node",strict:true,skipLibCheck:true,noEmit:true,types:[],lib:["ES2020","DOM"],baseUrl:ROOT,paths:{[packageInfo.name+"/*"]:["src/hardened-runtime/*"],"@laya/as3-runtime/*":["src/hardened-runtime/*"]}},files}));run(process.execPath,[path.join(ROOT,"node_modules/typescript-4-9/bin/tsc"),"-p",tsconfig,"--pretty","false"]);
 const ts=require("typescript-4-9"),entryPath=path.join(output,manifest.applicationEntryPath);for(const [index,name] of Object.keys(sources).entries())fs.writeFileSync(files[index].replace(/\.ts$/,".js"),ts.transpileModule(code[name],{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText);fs.writeFileSync(entryPath.replace(/\.ts$/,".js"),ts.transpileModule(fs.readFileSync(entryPath,"utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText);
 const application=Module.createRequire(entryPath.replace(/\.ts$/,".js"))(entryPath.replace(/\.ts$/,".js")),moduleFor=name=>application.AS3_APPLICATION_MODULES.find(module=>module[name])[name];
 const Probe=moduleFor("DateEpochCompiled"),probe=new Probe(),values=[0,-1,1,1234567890123,-1234567890123,.75,-.75,NaN,Infinity];for(const [index,value] of values.entries())assert.deepEqual(probe.exercise(value),epoch.capture.state.observations[index].result,String(value));
 const Time=moduleFor("TimeManagerEpoch"),sample=Date.UTC(2026,6,15,10,20,30);
 const setNative=new Date(sample);setNative.setMinutes(setNative.getMinutes()-(-480-setNative.getTimezoneOffset()));assert.equal(Time.setTimezoneOffset(sample).time,setNative.getTime());const resetNative=new Date(sample);resetNative.setMinutes(resetNative.getMinutes()+(-480-resetNative.getTimezoneOffset()));assert.equal(Time.reSetTimezoneOffset(sample).time,resetNative.getTime());const later=sample+86400000,nativeDiff=later-sample+(new Date(sample).getTimezoneOffset()-new Date(later).getTimezoneOffset())*60*1000;assert.equal(Time.getDiffTime(sample,later),nativeDiff);const original=Time.setTimezoneOffset(sample),clone=Time.clone(original);assert.notEqual(clone,original);assert.equal(clone.time,original.time);

 const hostile={StringArgument:["value:String","new Date(value);"],IntArgument:["value:int","new Date(value);"],UintArgument:["value:uint","new Date(value);"],DynamicArgument:["value:*","new Date(value);"],ObjectArgument:["value:Object","new Date(value);"],BooleanArgument:["value:Boolean","new Date(value);"],DateArgument:["value:Date","new Date(value);"],NullArgument:["","new Date(null);"],UndefinedArgument:["","new Date(undefined);"],TwoArguments:["","new Date(0,1);"]};
 for(const [name,[parameters,body]] of Object.entries(hostile))fs.writeFileSync(path.join(source,name+".as"),`package {public class ${name} {public function run(${parameters}):void {var held:Date=${body.slice(0,-1)};}}}`);
 fs.rmSync(profile,{recursive:true,force:true});makeProfile();compile("qualify","hostile");const rows=JSON.parse(fs.readFileSync(path.join(temporary,"hostile/manifest.json"))).files;
 for(const name of Object.keys(hostile)){const row=rows.find(item=>item.sourcePath===name+".as");assert.equal(row?.status,"held",JSON.stringify(row));}
 for(const name of ["StringArgument","IntArgument","UintArgument","DynamicArgument","ObjectArgument","BooleanArgument","DateArgument"])assert.equal(rows.find(item=>item.sourcePath===name+".as").code,"HARDENED_DATE_CONSTRUCTOR_TYPE");assert.equal(rows.find(item=>item.sourcePath==="TwoArguments.as").code,"HARDENED_DATE_CONSTRUCTOR_ARITY");
});
