"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),crypto=require("node:crypto"),ts=require("typescript-4-9");
const root=path.resolve(__dirname,"../.."),laya=process.env.HARDENED_FIXTURE_LAYA,sha=value=>crypto.createHash("sha256").update(value).digest("hex");
const canonical=value=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?"["+value.map(canonical).join(",")+"]":"{"+Object.keys(value).sort().map(key=>JSON.stringify(key)+":"+canonical(value[key])).join(",")+"}";
const modules=new Map();function load(file){if(modules.has(file))return modules.get(file).exports;const module={exports:{}};modules.set(file,module);const out=ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText;Function("require","module","exports",out)(name=>name.startsWith(".")?load(path.resolve(path.dirname(file),name+".ts")):require(name),module,module.exports);return module.exports;}
const api=load(path.join(root,"src/hardened/native-uri-component-authority.ts")),sources=load(path.join(root,"src/hardened/source-member-authority.ts"));
const SDK="e0f81fdb2029d2bb16e6987c8d85d4eba5eedfa3a23ed6e7f780bf6eb67b0546",DECLARATION="7825ee4f0a278edbbdec0f78065a886c4692c36c0ef189ae1ab7bde32db7fe47",RUNTIME="2264c65a2c22fa66d4d14b97b299fe88ba0342f924cc948bf20df159c5cee8bf";
function source(){const json=canonical({schema:"as3-source-member-authority@1",generator:"air-sdk-swfdump-abc@1",sourceArtifactSha256:SDK,entryCount:1,entries:[{qname:"Object",baseQName:null,ownInstanceMemberNames:[]}]})+"\n";return sources.loadSourceMemberAuthority(json,sha(json),sha);}
test("URI authority brand is unavailable without an exact retained proof",()=>{const value=source();assert.equal(api.nativeUriComponentAuthoritySha256(value),null);assert.throws(()=>api.verifyNativeUriComponentAuthority({...value},"/unread","{}","{}"));assert.equal(api.nativeUriComponentAuthoritySha256({...value}),null);});
test("URI authority authenticates exact SDK/runtime/evidence bytes and rejects substitution",{skip:!laya},t=>{
 const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),"native-uri-authority-")));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const evidenceRoot=path.join(fs.realpathSync(laya),"tests/nativeFlashOracle/encode-uri-component"),destination=path.join(dir,"native-uri-component");fs.mkdirSync(destination);
 const declaration='package\r\n{\r\n   [native("Toplevel::encodeURIComponent")]\r\n   public native function encodeURIComponent(param1:String = "undefined") : String;\r\n}\r\n\r\nimport avmplus.*;\r\n\r\nuse namespace AS3;\r\n\r\n';
 assert.equal(sha(declaration),DECLARATION);fs.writeFileSync(path.join(destination,"encodeURIComponent.as"),declaration);
 const signatures=canonical({inputs:{"profile/sdk-source/scripts/encodeURIComponent.as":DECLARATION}})+"\n";fs.writeFileSync(path.join(destination,"sdk-signatures.json"),signatures);
 const expected={"EncodeURIComponentProbe.as":"d02d738d978520fd8b4a6288393042c8d2e775d6a46ca830ba489abbd1fd6e6e","README.md":"fcbd516f77cd15d8800c2754f2bef2e765b47bf6a020f01363ce28adb5494967","browser-air.json":"427ae9b7408c6da2026090df4e3321af78719d49ea77e2e2d8046d8853f85adf","browser-pin.json":"42c5d4efebeb0eba8e4f98c9efd8b8529435033b35432b56188d14c0f61879b2","native-air.json":"6e6fb03ff5373b9d57f2b4ce9f2b877619b48c12b93c789191780baa0fa470b2","run-browser.mjs":"b8def9ff4b3446822336d98b34e494ea6bce2acad2e05b4a53db15ef8d9b7def","scenario.json":"7e8cb57dba7c5fc74d7f818cd3072da68e2298c071b76ff1116be647de5bbd79"};
 const evidence=Object.entries(expected).sort().map(([name,digest])=>{const bytes=fs.readFileSync(path.join(evidenceRoot,name));assert.equal(sha(bytes),digest);fs.writeFileSync(path.join(destination,name),bytes);return{name,path:"native-uri-component/"+name,sha256:digest};});
 const proof={schema:"as3-native-uri-component-authority@1",sourceArtifactSha256:SDK,declarationPath:"native-uri-component/encodeURIComponent.as",declarationSha256:DECLARATION,signaturesPath:"native-uri-component/sdk-signatures.json",signaturesSha256:sha(signatures),evidenceRevision:"1563e72a6f3849554c3ccb3eacd615fd3083f435",evidence,runtime:{module:"@laya/as3-runtime/AS3URI",export:"as3EncodeURIComponent",sourcePath:"src/hardened-runtime/AS3URI.ts",sourceSha256:RUNTIME}};
 const manifest={nativeSdkSha256:SDK,nativeSignaturesSha256:sha(signatures),nativeUriComponentDeclarationSha256:DECLARATION,nativeUriComponentEvidenceRevision:proof.evidenceRevision,nativeUriComponentRuntimeSourceSha256:RUNTIME};
 const proofJson=canonical(proof)+"\n",manifestJson=canonical(manifest)+"\n",valid=source();api.verifyNativeUriComponentAuthority(valid,dir,proofJson,manifestJson);assert.equal(api.nativeUriComponentAuthoritySha256(valid),sha(proofJson));
 const reject=(candidate=proof,sourceManifest=manifest)=>{const value=source();assert.throws(()=>api.verifyNativeUriComponentAuthority(value,dir,canonical(candidate)+"\n",canonical(sourceManifest)+"\n"));assert.equal(api.nativeUriComponentAuthoritySha256(value),null);};
 reject({...proof,evidenceRevision:"0".repeat(40)});reject({...proof,runtime:{...proof.runtime,sourceSha256:"0".repeat(64)}});reject({...proof,evidence:[...proof.evidence].reverse()});reject({...proof,declarationPath:"../escape.as"});reject(proof,{...manifest,nativeUriComponentEvidenceRevision:"0".repeat(40)});
 fs.appendFileSync(path.join(destination,"native-air.json")," ");reject();
});
