const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),laya=process.env.HARDENED_FIXTURE_LAYA;
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const canonical=value=>value===null||typeof value!=='object'?JSON.stringify(value):Array.isArray(value)?'['+value.map(canonical).join(',')+']':'{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}';

test('Shared String.charCodeAt preserves AIR UTF-16 and index conversion behavior',async()=>{
 assert.ok(laya&&process.env.HARDENED_FIXTURE_AIR_SDK&&process.env.HARDENED_FIXTURE_FFDEC,'AIR, Laya and FFDec required');
 const evidence=path.join(laya,'tests/nativeFlashOracle/string-char-code-at'),read=name=>fs.readFileSync(path.join(evidence,name));
 for(const [file,expected] of Object.entries(JSON.parse(read('evidence-pin.json'))))assert.equal(hash(read(file)),expected);
 const receipt=JSON.parse(read('native-receipt.json')),captured=JSON.parse(read('native-capture.json'));
 assert.equal(receipt.status,'passed');assert.equal(receipt.capture.runs,2);assert.equal(receipt.capture.identical,true);assert.equal(receipt.capture.observationCount,17);assert.equal(captured.runtime.version,'MAC 51,3,3,2');
 assert.equal(hash(read('StringCharCodeAtProbe.as')),receipt.artifacts['source/StringCharCodeAtProbe.as']);assert.equal(hash(read('scenario.json')),receipt.scenario.sha256);
 const base=path.join(root,'.cache/string-char-code-at');fs.mkdirSync(base,{recursive:true});const dir=fs.realpathSync(fs.mkdtempSync(path.join(base,'run-'))),profile=path.join(dir,'profile'),source=path.join(dir,'source');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'StringCharCodeAtProbe.as'),read('StringCharCodeAtProbe.as'));
 const run=(cmd,args)=>{const r=cp.spawnSync(cmd,args,{cwd:root,encoding:'utf8',timeout:120000});assert.equal(r.status,0,r.stdout+r.stderr);return r;};
 run('python3',['-B','tools/create-fixture-profile.py','--source',source,'--entry','StringCharCodeAtProbe','--air-sdk',process.env.HARDENED_FIXTURE_AIR_SDK,'--laya',laya,'--ffdec-jar',process.env.HARDENED_FIXTURE_FFDEC,'--shared-string-ranges','--output',profile]);
 const args=out=>[source,path.join(dir,out),'--source-census',path.join(profile,'census.json'),'--target-capabilities',path.join(laya,'docTool/architecture/authored-content-capabilities.json'),'--profile-lock',path.join(profile,'profile-lock.json')];
 run(process.execPath,['bin/as3-frontend','transpile',...args('emitted')]);
 const output=path.join(dir,'emitted/__as3_runtime'),manifest=JSON.parse(fs.readFileSync(path.join(dir,'emitted/manifest.json'))),application=fs.readFileSync(path.join(dir,'emitted',manifest.files[0].typescriptPath),'utf8');
 assert.match(application,/sourceStringCharCodeAt as __sharedStringCharCodeAt/);assert.match(application,/__sharedStringCharCodeAt\(/);
 const typeConfig=path.join(dir,'generated-tsconfig.json');fs.writeFileSync(typeConfig,JSON.stringify({compilerOptions:{target:'ES2020',module:'CommonJS',moduleResolution:'node',strict:true,strictNullChecks:true,strictPropertyInitialization:true,experimentalDecorators:true,skipLibCheck:true,noEmit:true,types:[],lib:['ES2020','DOM'],baseUrl:root,paths:{'@laya/as3-runtime/*':['src/hardened-runtime/*'],'laya/*':[path.join(laya,'src/layaAir/*')]}},files:[path.join(dir,'emitted',manifest.files[0].typescriptPath)]}));run(process.execPath,[path.join(root,'node_modules/typescript-4-9/bin/tsc'),'-p',typeConfig,'--pretty','false']);
 const steps=JSON.parse(read('scenario.json')).steps,wanted=captured.state.observations,esbuild=require('esbuild'),entry=`import {startAS3Application} from ${JSON.stringify(path.join(output,'ApplicationEntry.generated.js'))};const probe=startAS3Application(new AbortController().signal);globalThis.stringCharCodeAt=${JSON.stringify(steps)}.map(step=>{for(const call of step.calls)probe[call.method](...call.args);return {id:step.id,result:probe.result};});`;
 const built=await esbuild.build({plugins:[{name:'shared-laya',setup(build){build.onResolve({filter:/^laya\//},args=>({path:path.join(laya,'src/layaAir',args.path.slice(5)+'.ts')}));}}],stdin:{contents:entry,resolveDir:root,loader:'js'},bundle:true,write:false,format:'iife',platform:'browser',target:'es2020'});const bundle=built.outputFiles[0].text;fs.writeFileSync(path.join(dir,'bundle.js'),bundle);
 const node=JSON.parse(JSON.stringify(new Function(bundle+';return globalThis.stringCharCodeAt;')()));assert.deepEqual(node,wanted);
 const {chromium}=require(process.env.LAYA_PLAYWRIGHT_MODULE||'playwright'),browser=await chromium.launch({headless:true});let web;try{const page=await browser.newPage({timezoneId:'Europe/Rome'});await page.addScriptTag({content:bundle});web=await page.evaluate(()=>JSON.parse(JSON.stringify(globalThis.stringCharCodeAt)));}finally{await browser.close();}assert.deepEqual(web,wanted);
 assert.equal(hash(fs.readFileSync(path.join(source,'StringCharCodeAtProbe.as'))),hash(read('StringCharCodeAtProbe.as')));
 const lockPath=path.join(profile,'profile-lock.json'),originalLock=fs.readFileSync(lockPath),lock=JSON.parse(originalLock);delete lock.files.stringRangeProvider;fs.writeFileSync(lockPath,canonical(lock)+'\n');run(process.execPath,['bin/as3-frontend','qualify',...args('without-provider')]);const held=JSON.parse(fs.readFileSync(path.join(dir,'without-provider/manifest.json'))).files[0];assert.equal(held.status,'held');assert.equal(held.code,'HARDENED_MEMBER_TARGET');fs.writeFileSync(lockPath,originalLock);
 const providerPath=path.join(profile,JSON.parse(originalLock).files.stringRangeProvider.path),savedProvider=fs.readFileSync(providerPath),proof=JSON.parse(savedProvider);try{proof.targetSources['src/layaAir/flash/utils/AS3StringIntrinsics.ts']='0'.repeat(64);fs.writeFileSync(providerPath,canonical(proof)+'\n');const forged=JSON.parse(originalLock);forged.files.stringRangeProvider.sha256=hash(fs.readFileSync(providerPath));fs.writeFileSync(lockPath,canonical(forged)+'\n');const rejected=cp.spawnSync(process.execPath,['bin/as3-frontend','qualify',...args('forged-provider')],{cwd:root,encoding:'utf8',timeout:120000});assert.notEqual(rejected.status,0);assert.match(rejected.stdout+rejected.stderr,/String range provider|STRING_RANGE_PROVIDER/);}finally{fs.writeFileSync(providerPath,savedProvider);fs.writeFileSync(lockPath,originalLock);}
 fs.writeFileSync(path.join(source,'ExtraArgument.as'),'package {public class ExtraArgument{public function call(text:String):Number{return text.charCodeAt(0,1);}}}');fs.writeFileSync(path.join(source,'MethodValue.as'),'package {public class MethodValue{public function call(text:String):Function{return text.charCodeAt;}}}');
 const boundaryProfile=path.join(dir,'boundary-profile');run('python3',['-B','tools/create-fixture-profile.py','--source',source,'--entry','StringCharCodeAtProbe','--air-sdk',process.env.HARDENED_FIXTURE_AIR_SDK,'--laya',laya,'--ffdec-jar',process.env.HARDENED_FIXTURE_FFDEC,'--shared-string-ranges','--output',boundaryProfile]);run(process.execPath,['bin/as3-frontend','qualify',source,path.join(dir,'boundary-output'),'--source-census',path.join(boundaryProfile,'census.json'),'--target-capabilities',path.join(laya,'docTool/architecture/authored-content-capabilities.json'),'--profile-lock',path.join(boundaryProfile,'profile-lock.json')]);const rows=JSON.parse(fs.readFileSync(path.join(dir,'boundary-output/manifest.json'))).files;assert.equal(rows.find(row=>row.sourcePath==='ExtraArgument.as').code,'HARDENED_STRING_ARITY');assert.equal(rows.find(row=>row.sourcePath==='MethodValue.as').code,'HARDENED_MEMBER_TARGET');
 fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify({rows:17,node,web,sourceUnchanged:true,applicationStart:true,rejectionGuards:2,providerGuards:2,typecheck:{strict:true,diagnostics:0}},null,2)+'\n');console.log(JSON.stringify({dir,rows:17,realms:['Node','Chromium'],status:'passed'}));
});
