const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const api = require('../../lib'), model = require('../../lib/emit/native-source-unit');
const {planNativeSourceNamespaces} = require('../../lib/emit/native-source-namespaces');
const declarations = require('../../lib/emit/native-generated-declarations');
const K = require('../../lib/syntax/nodeKind').default;
const rows = require('../native-namespace-updates/verify-evidence.cjs');
const hash = source => crypto.createHash('sha256').update(source).digest('hex');
const source = fs.readFileSync(path.join(__dirname, '../native-namespace-updates/source/updatecases/slot.as'), 'utf8');
const unit = (owner, source) => model.readNativeSourceUnit(owner, source, hash(source));
const slot = unit('updatecases.slot', source), descriptor = slot.namespaces[0];
assert.equal(slot.declarations.length, 0);
assert.equal(slot.namespaces.length, 1);
assert.deepEqual(descriptor, {sourceOwner: 'updatecases.slot', name: 'slot', packageQName: 'updatecases.slot', filePrivate: false, kind: 'namespace'});
assert(Object.isFrozen(slot) && Object.isFrozen(slot.namespaces) && Object.isFrozen(descriptor));
assert(!('reflectedName' in descriptor));
const ast = model.nativeSourceUnitAst(slot);
assert.equal(ast.namespaces[0].node.kind, K.NAMESPACE_DECLARATION);
assert(source.slice(ast.namespaces[0].node.start, ast.namespaces[0].node.end).includes('public namespace slot'));
ast.namespaces[0].node.children.length = 0;
assert.equal(model.nativeSourceUnitNode(slot, descriptor).children[2].text, '"urn:as3-to-ts:namespace-updates"');
const alias = unit('aliases.alias', 'package aliases {import updatecases.slot; public namespace alias=slot;}');
const chain = unit('aliases.chain', 'package aliases {public namespace chain=alias;}');
const wildcard = unit('consumer.selected', 'package consumer {import aliases.*; public namespace selected=chain;}');
const mixed = unit('mixed.Box', 'package mixed {public namespace same="urn:as3-to-ts:namespace-updates"; public namespace alias=same; public class Box {}}');
const units = new Map([slot, alias, chain, wildcard, mixed].map(u => [u.owner, u]));
const bindings = planNativeSourceNamespaces(units);
assert.equal(bindings.length, 6);
assert(bindings.every(b => b.uri === 'urn:as3-to-ts:namespace-updates' && Object.isFrozen(b)));
assert.equal(bindings.find(b => b.qname === 'aliases.alias').aliasOf, 'updatecases.slot');
assert.equal(bindings.find(b => b.qname === 'aliases.chain').aliasOf, 'aliases.alias');
assert.equal(bindings.find(b => b.qname === 'consumer.selected').aliasOf, 'aliases.chain');
assert.equal(bindings.find(b => b.qname === 'mixed.alias').sourceOwner, 'mixed.Box');
assert.equal(bindings.find(b => b.qname === 'updatecases.slot').declaration, descriptor);
const sources = Object.fromEntries(Array.from(units).map(([q, u]) => [q, {source: u.source, sourceSha256: u.sourceSha256}]));
const plan = api.createNativeGeneratedDeclarationPlan({scope: 'namespace-source-planning', providerModule: './provider', sources});
assert.equal(plan.namespaces.length, 6);
assert.deepEqual(plan.bindings.map(b => b.qname), ['mixed.Box']);
assert.equal(plan.interfaces.length, 0);
assert.equal(plan.privateBindings.length, 0);
assert.deepEqual(Object.keys(plan.sourceHashes).sort(), Object.keys(sources).sort());
assert(!plan.moduleSource.includes('urn:as3-to-ts:namespace-updates'));
assert.equal(declarations.nativeGeneratedSourceUnit(plan, 'updatecases.slot').source, source);
let guards = 0;
const reject = (fn, pattern = /AS3_(SOURCE_UNIT|SOURCE_NAMESPACE|GENERATED_DECLARATIONS|NAMESPACE|SOURCE_CLASS_MODULE)_UNSUPPORTED/) => {
  assert.throws(fn, pattern); guards++;
};
reject(() => model.nativeSourceUnitNode(slot, {...descriptor}));
reject(() => model.nativeSourceUnitNode(alias, descriptor));
reject(() => model.nativeSourceUnitAst(JSON.parse(JSON.stringify(slot))));
reject(() => planNativeSourceNamespaces(new Map([[slot.owner, JSON.parse(JSON.stringify(slot))]])));
reject(() => model.readNativeSourceUnit(slot.owner, source + ' ', slot.sourceSha256));
reject(() => unit('updatecases.other', source));
reject(() => planNativeSourceNamespaces(new Map([['wrong.Owner', slot]])));
const bad = (owner, source, extra = []) => reject(() => planNativeSourceNamespaces(new Map([unit(owner, source), ...extra].map(u => [u.owner, u]))));
bad('a.bad', 'package a {public namespace bad=unknown;}');
bad('a.bad', 'package a {public namespace bad="";}');
bad('a.bad', 'package a {public namespace bad="urn:escaped\\n";}');
bad('a.bad', 'package a {public namespace bad=make();}');
bad('a.bad', 'package a {public namespace bad=7;}');
bad('a.bad', 'package a {public namespace bad=bad;}');
bad('a.first', 'package a {public namespace first=second;}', [unit('a.second', 'package a {public namespace second=first;}')]);
bad('a.bad', 'package a {public namespace bad=Box;}', [unit('a.Box', 'package a {public class Box {}}')]);
bad('a.bad', 'package a {public namespace bad=Object;}');
bad('a.bad', 'package a {import updatecases.slot; import other.slot; public namespace bad=slot;}', [slot, unit('other.slot', 'package other {public namespace slot="urn:other";}')]);
bad('a.bad', 'package a {import updatecases.*; import other.*; public namespace bad=slot;}', [slot, unit('other.slot', 'package other {public namespace slot="urn:other";}')]);
bad('mixed.same', 'package mixed {public namespace same="urn:duplicate";}', [mixed]);
bad('mixed.same', 'package mixed {public class same {}}', [mixed]);
bad('a.bad', 'package a {internal namespace bad="urn:internal";}');
bad('a.bad', 'package a {public namespace bad="urn:one"; public namespace other="urn:two";}');
bad('a.bad', 'package a {public namespace bad="urn:one"; public var lost:int=1;}');
bad('a.bad', 'package a {public namespace bad="urn:one"; public const lost:int=1;}');
bad('a.bad', 'package a {public namespace bad="urn:one"; public function lost():void {}}');
bad('a.bad', 'package a {public namespace bad="urn:one";} class Helper {}');
bad('a.Box', 'package a {public namespace Box="urn:collision"; public class Box {}}');
reject(() => declarations.nativeGeneratedClassDeclaration(plan, 'updatecases.slot'));
reject(() => declarations.nativeGeneratedDeclarationNode(plan, 'updatecases.slot'));
reject(() => api.emitNativeSourceClassModule({plan}), /source namespace value publication requires qualification/);
reject(() => api.createNativeGeneratedDeclarationPlan({scope:'bad', providerModule:'./provider', sources:{'mixed.Box':sources['mixed.Box']}, providers:{'mixed.same':{module:'./provider',exportName:'same'}}}));
reject(() => api.createNativeGeneratedDeclarationPlan({scope:'bad', providerModule:'./provider', sources:{'mixed.Box':{...sources['mixed.Box'],referenceOnly:true}}}));
const inherited = 'package updatecases {public class Invalid extends slot {}}';
reject(() => api.createNativeGeneratedDeclarationPlan({scope:'bad',providerModule:'./provider',sources:{'updatecases.slot':sources['updatecases.slot'],'updatecases.Invalid':{source:inherited,sourceSha256:hash(inherited)}}}), /base requires a planned source declaration/);
const typed = 'package updatecases {public class Invalid {public var value:slot;}}';
const typedPlan = api.createNativeGeneratedDeclarationPlan({scope:'typed',providerModule:'./provider',sources:{'updatecases.slot':sources['updatecases.slot'],'updatecases.Invalid':{source:typed,sourceSha256:hash(typed)}}});
assert.equal(typedPlan.references.find(r => r.sourceName === 'slot').kind, 'unresolved');
assert.equal(typedPlan.references.find(r => r.sourceName === 'slot').identity, 'updatecases.slot');
const parsed = require('../../lib/parse')('PackageStorage.as', 'package storage {public var kept:int=1; public const fixed:int=2;}');
const normalize = node => {node.children = node.children.filter(Boolean); node.children.forEach(normalize);}; normalize(parsed);
const storage = parsed.findChild(K.PACKAGE).findChild(K.CONTENT);
assert.equal(storage.findChild(K.VAR_LIST).findChild(K.NAME_TYPE_INIT).findChild(K.NAME).text, 'kept');
assert.equal(storage.findChild(K.CONST_LIST).findChild(K.NAME_TYPE_INIT).findChild(K.NAME).text, 'fixed');
console.log(JSON.stringify({qualification:'source namespace identity/alias planning; runtime value publication remains held',authenticatedExistingAIRRows:rows.length,plannedNamespaces:plan.namespaces.length,guards}));
