const fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
const here=__dirname,owner=path.resolve(here,'../..'),compiler=path.resolve(process.env.COMPILER_CHECKOUT||owner),engine=path.resolve(process.env.LAYAAIR_CHECKOUT||path.join(owner,'../LayaAir-op2'));
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),esbuild=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||require.resolve('playwright',{paths:[owner,engine]}));const {fixture}=require(path.join(compiler,'tests/native-instance-initializers/callable-fixture'));const {verify,invalid,hash}=require('./evidence.cjs');
const pin='3d7c64062e899c8aaf4abd141da5c0d4c01f2a4d';const output=path.join(owner,'.cache/native-foreach-receivers');fs.mkdirSync(output,{recursive:true});const run=fs.mkdtempSync(path.join(output,'run-')),providerRoot=path.join(run,'engine');fs.mkdirSync(providerRoot);
const archive=cp.execFileSync('git',['archive','--format=tar',pin,'src/layaAir/flash/utils'],{cwd:engine,maxBuffer:32*1024*1024});cp.execFileSync('tar',['-xf','-','-C',providerRoot],{input:archive});
const modules=['AS3MethodBinding','AS3Coercion'],utils=path.join(providerRoot,'src/layaAir/flash/utils');const bundled=esbuild.buildSync({stdin:{contents:modules.map(n=>'export * from "./src/layaAir/flash/utils/'+n+'";').join('\n'),resolveDir:providerRoot,loader:'ts'},bundle:true,write:false,metafile:true,platform:'node',format:'cjs',target:'es2015'});const common='(function(){var module={exports:{}};'+bundled.outputFiles[0].text+';Object.assign(exports,module.exports);})();';
const diagnostics=p=>modern.getPreEmitDiagnostics(p).map(d=>({code:d.code,file:d.file&&path.relative(run,d.file.fileName),text:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));
const provider=modern.createProgram(modules.map(n=>path.join(utils,n+'.ts')),{target:modern.ScriptTarget.ES2020,module:modern.ModuleKind.CommonJS,declaration:true,emitDeclarationOnly:true,rootDir:utils,outDir:path.join(run,'provider'),lib:['lib.es2020.d.ts']});assert.deepStrictEqual(diagnostics(provider),[]);assert.equal(provider.emit().emitSkipped,false);
function exercise(Subject,Journal,count){const rows=[];for(let mode=0;mode<count;mode++){Journal.rows=[];new Subject(mode);rows.push({mode,trace:Array.from(Journal.rows)});}return rows;}
function rejectBindings(){const parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit'));const options={customVisitors:[],definitionsByNamespace:{}};assert.throws(()=>emit(parse('ForEachSimple.as',invalid().source),invalid().source,options),/AS3_FOREACH_UNSUPPORTED: unresolved iterator binding: value/);const results=[];for(const body of ['var values:Array=[1,2];var value:*;for each(value in values){}','var values:Array=[1,2];for each(var value in values){}','var value:*;if(true)for each(value in [1,2])value=value;else value=2;']){const source='package { public class Subject { public function Subject(){'+body+'} } }',text=emit(parse('Subject.as',source),source,options);assert.deepStrictEqual(ts.createSourceFile('Subject.ts',text,ts.ScriptTarget.ES2015,true).parseDiagnostics,[]);assert(!text.includes('import { undefined }'));results.push({parseable:true});}
 const source='package held { public class Subject { public function Subject() { var values:Array=[1,2]; var value:*; for each(value in values){} } } }';const metadata={module:'./AS3MethodBinding',classes:{'held.Subject':{sourceSha256:hash(source),metadata:{name:'held::Subject',base:'Object',isDynamic:false,isFinal:false,instance:{variables:[],constants:[],methods:[],accessors:[]},statics:{variables:[],constants:[],methods:[],accessors:[{name:'prototype',declaredBy:'Class',access:'readonly'}]}},instanceTraits:[],staticTraits:[]}}};assert.throws(()=>fixture(ts.ScriptTarget.ES2015,{'held.Subject':source},common,metadata),/AS3_SOURCE_OPERATION_UNSUPPORTED: source enumeration/);return {declaredForms:results.length,missingBindingRejected:true,metadataEnumerationStillRejected:true};}
(async()=>{const reports=[],browser=await chromium.launch({headless:true});try{
for(const group of ['receivers','control-flow'])for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015]){const input=verify(group),native=fixture(target,input.sources,common),actual=exercise(native.get('Subject'),native.get('Journal'),input.expected.length);assert.deepStrictEqual(actual,input.expected);const dir=path.join(run,group+'-'+target);fs.mkdirSync(dir);const generated={};for(const n of ['bound','classBound','nativeClass','callableClass'])generated[n]=fs.readFileSync(path.join(compiler,'utils',n+'.ts'),'utf8');Object.assign(generated,native.generated);for(const[n,s]of Object.entries(generated))fs.writeFileSync(path.join(dir,n+'.ts'),s);fs.writeFileSync(path.join(dir,'AS3MethodBinding.d.ts'),'export * from "../provider/AS3MethodBinding";export * from "../provider/AS3Coercion";');fs.writeFileSync(path.join(dir,'Consumer.ts'),'import {Subject} from "./Subject";import {readNativeClass} from "./nativeClass";const value:Subject=new (readNativeClass(Subject))(0);const calls:number=value.calls;');const program=modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{target,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,allowUnreachableCode:true,lib:['lib.es2015.d.ts'],experimentalDecorators:true,noEmit:true});const errors=diagnostics(program);fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(errors,null,2));assert.deepStrictEqual(errors,[]);
 const specs=[{name:'AS3MethodBinding',code:common}];for(const[n,s]of Object.entries(generated)){const built=ts.transpileModule(s,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepStrictEqual(built.diagnostics,[]);specs.push({name:n,code:built.outputText});}const script=`{const modules=new Map();const specs=${JSON.stringify(specs)};for(const spec of specs)modules.set(spec.name,{});for(const spec of specs)new Function('exports','require',spec.code)(modules.get(spec.name),r=>{const n=r.split('/').pop();if(!modules.has(n))throw Error(r);return modules.get(n);});const read=modules.get('nativeClass').readNativeClass;globalThis.result=(${exercise.toString()})(read(modules.get('Subject').Subject),read(modules.get('Journal').Journal),${input.expected.length});}`;fs.writeFileSync(path.join(dir,'browser.js'),script);const page=await browser.newPage(),pageErrors=[];page.on('pageerror',e=>pageErrors.push(String(e)));await page.addScriptTag({content:script});const browserRows=await page.evaluate(()=>globalThis.result);assert.deepStrictEqual(browserRows,input.expected);assert.deepStrictEqual(pageErrors,[]);await page.close();fs.writeFileSync(path.join(dir,'rows.json'),JSON.stringify({node:actual,browser:browserRows},null,2));reports.push({group,target,rows:actual.length,nodeMatched:true,browserMatched:true,receiptSHA256:input.receiptSHA256,strictDiagnostics:errors,bundleSHA256:hash(script)});}
 const binding=rejectBindings();const report={scope:'Array foreach receiver/control-flow preservation only; host enumeration remains unadmitted for source metadata',engineCommit:pin,compiler,compilerTypeScript:ts.version,strictTypeScript:modern.version,strict:true,strictNullChecks:false,allowUnreachableCode:true,declarationAdaptation:false,browser:browser.version(),reports,binding,compilerInputs:['src/emit/emitter.ts','lib/emit/emitter.js'].map(f=>({path:f,sha256:hash(fs.readFileSync(path.join(compiler,f)))})),providerInputs:provider.getSourceFiles().filter(f=>f.fileName.startsWith(utils)).map(f=>({path:path.relative(providerRoot,f.fileName),sha256:hash(fs.readFileSync(f.fileName))}))};fs.writeFileSync(path.join(run,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({run,reports,binding}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
