const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),z=require('zlib'),cp=require('child_process');
const root=path.resolve(__dirname,'../..'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),archive=path.join(__dirname,'qualified.json.gz'),pinFile=path.join(__dirname,'pin.json');
const retaining=require.main===module&&process.argv[2]==='--retain';let packet,bytes,pin;
const records=r=>[...r.compilerInputs,...(r.results||r.runs).flatMap(v=>[...(v.inputs||[]),...(v.typecheck?.inputs||[]),...(v.typechecks||[]).flatMap(t=>t.inputs||[])])];
if(retaining){assert(!fs.existsSync(archive));const [reportFile,regressionFile,baselineFile]=process.argv.slice(3).map(f=>path.resolve(f));const report=JSON.parse(fs.readFileSync(reportFile)),regression=JSON.parse(fs.readFileSync(regressionFile));const files=new Map();
 const add=f=>{f=path.resolve(root,f);if(files.has(f))return;const b=fs.readFileSync(f);files.set(f,{file:f,sha256:hash(b),base64:b.toString('base64')});};
 const tree=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())tree(f);else add(f);}};
 for(const [r,f]of [[report,reportFile],[regression,regressionFile]]){tree(path.dirname(f));for(const i of records(r)){assert.equal(hash(fs.readFileSync(path.resolve(root,i.file))),i.sha256,i.file);add(i.file);}}
 tree(report.evidence);tree(path.join(root,'tests/native-generated-cast-receiver/oracle'));for(const f of ['run.cjs','observer.ts','guards.cjs','controls.cjs','verify.cjs','oracle-pin.json','expected.json'])add(path.join(root,'tests/native-generated-cast-receiver',f));add(baselineFile);for(const f of ['compile.cjs','run.cjs','observer.ts','guards.cjs','controls.cjs'])add(path.join(__dirname,f));
 packet={root,reportFile,regressionFile,baselineFile,baselineCommit:'8a2cc8dbd7d61f9598311be37eafa72e99a27adc',baselineEmitter:cp.execFileSync('git',['show','8a2cc8d:src/emit/emitter.ts'],{cwd:root,encoding:'utf8'}),files:[...files.values()]};bytes=z.gzipSync(JSON.stringify(packet),{level:9});pin={sha256:hash(bytes),bytes:bytes.length,files:files.size};
}else{bytes=fs.readFileSync(archive);pin=JSON.parse(fs.readFileSync(pinFile));packet=JSON.parse(z.gunzipSync(bytes));}
assert.equal(hash(bytes),pin.sha256);assert.equal(bytes.length,pin.bytes);const files=new Map(packet.files.map(i=>[path.resolve(i.file),i]));assert.equal(files.size,pin.files);
const read=f=>{const i=files.get(path.resolve(packet.root,f));assert(i,f);const b=Buffer.from(i.base64,'base64');assert.equal(hash(b),i.sha256,f);return b;},json=f=>JSON.parse(read(f));for(const f of files.keys())read(f);
const report=json(packet.reportFile),regression=json(packet.regressionFile),baseline=json(packet.baselineFile),receipt=json(path.join(report.evidence,'evidence/receipt.json'));
assert.equal(receipt.status,'passed');assert.equal(receipt.capture.runs,2);assert.equal(receipt.capture.identical,true);for(const [f,h]of Object.entries(receipt.artifacts)){assert.equal(hash(read(path.join(report.evidence,'evidence',f))),h);if(f.startsWith('source/'))assert.equal(hash(read(path.join(report.evidence,f))),h);}
const air=json(path.join(report.evidence,'evidence/run-1/capture.json'));assert.deepEqual(air,json(path.join(report.evidence,'evidence/run-2/capture.json')));assert.equal(air.state.failure,'');assert.equal(air.state.observations.length,6);
assert.equal(report.baseline,false);assert.deepEqual(report.results.map(v=>[v.target,v.variant]),[['ES5','source'],['ES2015','source']]);
for(const v of report.results){assert.deepEqual(v.diagnostics,[]);assert.deepEqual(v.node.rows,air.state.observations);assert.deepEqual(v.web,v.node);assert.equal(v.guards.length,3);assert.equal(v.controls.length,2);assert.deepEqual(v.controls[0].codes,[2695,2695,2695,2695,2695,2695]);assert.match(v.controls[1].node.error,/Cannot read properties of null/);assert.deepEqual(v.controls[1].web,v.controls[1].node);for(const [q,s]of Object.entries(v.sources)){assert.equal(hash(s.source),s.sourceSha256);if(v.variant==='source')assert.equal(s.source,read(path.join(report.evidence,'source',q.replaceAll('.','/')+'.as')).toString());}}
for(const r of [report,regression])for(const i of records(r))assert.equal(hash(read(i.file)),i.sha256,i.file);
assert.equal(baseline.baseline,true);for(const v of baseline.results){assert.equal(v.diagnostics.length,6);assert.match(v.node.error,/Cannot read properties of null/);assert.deepEqual(v.node,v.web);}assert(packet.baselineEmitter.includes("emitter.insert('(');visitNode(emitter,type);"));
const oldAir=json(path.join(packet.root,'tests/native-generated-cast-receiver/oracle/run-1/capture.json'));assert.equal(oldAir.state.observations.length,14);assert.equal(regression.results.length,2);
for(const v of regression.results){assert.equal(v.rejectionGuards,8);for(const t of v.typechecks)assert.deepEqual(t.diagnostics,[]);assert.deepEqual(v.node.rows,oldAir.state.observations);assert.deepEqual(v.node,v.web);assert.equal(v.mutations.length,1);assert.notDeepEqual(v.mutations[0].node.rows,oldAir.state.observations);assert.deepEqual(v.mutations[0].node,v.mutations[0].web);}

if(retaining||require.main===module&&process.argv.includes('--check-current'))for(const [f,i]of files)assert.equal(hash(fs.readFileSync(f)),i.sha256,f);
if(retaining){fs.writeFileSync(archive,bytes,{flag:'wx'});fs.writeFileSync(pinFile,JSON.stringify(pin,null,2)+'\n',{flag:'wx'});}
console.log(JSON.stringify({status:'verified-own-class-cast',rows:6,targets:2,realms:2,variants:1,guards:3,mutations:2,typeErrors:0,regressionRows:14,archive:pin}));module.exports={packet,read,report,regression};
