const assert=require('assert/strict'),api=require('../../lib');
const {nativeGeneratedDeclarationInputs}=require('../../lib/emit/native-generated-declarations');
const {generatedNamespaceAncestry}=require('../../lib/emit/native-generated-namespaces');
const {createNativeSourceAncestryPlan}=require('../../lib/emit/native-source-ancestry');
const {sources,hash}=require('./compile.cjs');
module.exports=config=>{
 const emit=plan=>api.emitNativeSourceClassModule({...config,plan,emitterOptions:{...config.emitterOptions,nativeReferenceCoercion:{...config.emitterOptions.nativeReferenceCoercion,plan}}});
 const plan=config.plan,input=nativeGeneratedDeclarationInputs(plan,plan.scope),guards=[];
 const expect=(name,fn,re)=>{assert.throws(fn,re);guards.push(name);};
 const provider=input.providers['flash.events.EventDispatcher'];
 for(const change of [{exportName:'Sprite'},{nativeBase:'Sprite'}])expect('incorrect native authority',()=>api.createNativeGeneratedDeclarationPlan({...input,providers:{'flash.events.EventDispatcher':{...provider,...change}}}),/exact supported/);
 const bare=api.createNativeGeneratedDeclarationPlan({...input,providers:{'flash.events.EventDispatcher':{module:provider.module,exportName:provider.exportName}},sources:{'cases.Unused':{source:'package cases { public class Unused {} }',sourceSha256:hash('package cases { public class Unused {} }')}},classScriptSources:undefined});
 assert.equal(generatedNamespaceAncestry(bare).classes['flash.events.EventDispatcher'],undefined);guards.push('reference provider has no ancestry authority');
 const missing={...input,providers:{}};expect('missing provider',()=>api.createNativeGeneratedDeclarationPlan(missing),/AS3_GENERATED_DECLARATIONS_UNSUPPORTED/);
 const dynamic=sources['cases.NamespaceBase'].source.replace('public class NamespaceBase','public dynamic class NamespaceBase');
 const bad=api.createNativeGeneratedDeclarationPlan({...input,sources:{...sources,'cases.NamespaceBase':{source:dynamic,sourceSha256:hash(dynamic)}}});
 expect('dynamic source ancestry',()=>emit(bad),/dynamic/);
 expect('provider source collision',()=>createNativeSourceAncestryPlan({sources:{'flash.events.EventDispatcher':{source:'package flash.events { public class EventDispatcher {} }',sourceSha256:hash('package flash.events { public class EventDispatcher {} }')}},providerClasses:{'flash.events.EventDispatcher':{dynamic:false,members:[]}}}),/collides/);
 const fs=require('fs'),path=require('path'),{evidence}=require('./compile.cjs');
 const original=fs.readFileSync(path.join(evidence,'../source/cases/NamespaceBase.as'),'utf8');
 const held=api.createNativeGeneratedDeclarationPlan({...input,sources:{...sources,'cases.NamespaceBase':{source:original,sourceSha256:hash(original)}}});
 assert.equal(typeof emit(held).moduleSource,'string');guards.push('qualified native listener super calls');
 const update=sources['cases.NamespaceOpened'].source.replace('this.alpha::amount = 3','++this.value');
 const inherited=api.createNativeGeneratedDeclarationPlan({...input,sources:{...sources,'cases.NamespaceOpened':{source:update,sourceSha256:hash(update)}}});
 expect('inherited namespace integer update remains held',()=>emit(inherited),/namespace update requires an own instance integer member/);
 const Module=require('module');
 const mutateModule=(name,replace)=>{const file=require.resolve('../../lib/emit/'+name),original=fs.readFileSync(file,'utf8'),changed=replace(original);assert.notEqual(changed,original);const m=new Module(file,module);m.filename=file;m.paths=module.paths;m._compile(changed,file);return m.exports;};
 const missingBoundary=mutateModule('native-generated-namespaces',s=>s.replace("const dispatcher = plan.nativeBindings.some(binding => binding.qname === 'flash.events.EventDispatcher' && !!binding.nativeBaseExport);","const dispatcher = false;"));
 expect('mutation: remove native namespace boundary',()=>missingBoundary.generatedNamespaces(plan,'cases.NamespaceBase'),/namespace inheritance requires a proven same-file ordinary base: EventDispatcher/);
 const walk=mutateModule('native-generated-proxy',s=>s.replace(/if \(plan\.nativeBindings\.some\(b => b\.qname === binding\.base && !!b\.nativeBaseExport\)\)\s+return undefined;/,'/* mutation: traverse native base as source */'));
 expect('mutation: traverse native Proxy boundary',()=>walk.generatedProxyNamespace(plan,'cases.NamespaceChild'),/exact planned source-unit capability required/);
 return guards;
};
