const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('node:assert/strict'),crypto=require('crypto'),vm=require('vm');
const compiler=path.resolve(__dirname,'../..'),engine=process.env.LAYA_ENGINE_REPOSITORY;
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),esbuild=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE),parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit'));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p));
assert.equal(sha(path.join(__dirname,'files.json')),'2ff554b0024db49922f6a33c9924a501e091d9001f8fadffd2a1190985d33303');
for(const f of json(path.join(__dirname,'files.json')))assert.equal(sha(path.join(__dirname,f.path)),f.sha256,f.path);
const evidence=path.join(__dirname,'evidence'),expected=json(path.join(evidence,'flash.json')).rows;assert.equal(expected.length,47);assert.deepEqual(json(path.join(__dirname,'repeat-evidence/flash.json')),json(path.join(evidence,'flash.json')));const negatives=[x=>x.pop(),x=>x.reverse(),x=>{x.find(r=>r.id==='compound-rhs-write').value[0]=22.8;},x=>{x.find(r=>r.id==='uint-prefix-overflow').value[0]=0;}];for(const mutate of negatives){const bad=structuredClone(expected);mutate(bad);assert.throws(()=>assert.deepEqual(bad,expected));}
const dependencyPath=path.join(__dirname,'addition-dependency.json');
assert.equal(sha(dependencyPath),'2eaae04e5c536f7472b8f5b511b250301a1c81346880c37c60a4b36df6289768');
const dependency=json(dependencyPath);assert.equal(dependency.sourceMode,'committed-engine');
assert.match(dependency.engineCommit,/^[a-f0-9]{40}$/);assert.equal(cp.execFileSync('git',['rev-parse',dependency.engineCommit+'^{commit}'],{cwd:engine,encoding:'utf8',windowsHide:true}).trim(),dependency.engineCommit);
const source=read(path.join(evidence,'sources/original/probe/TypedLocals.as')),qname='probe.TypedLocals';
const metadata=JSON.parse(cp.execFileSync(process.env.PYTHON,[path.join(__dirname,'extract-metadata.py'),evidence],{encoding:'utf8',windowsHide:true}));
const options={customVisitors:[],definitionsByNamespace:{probe:['TypedLocals']},nativeClassInitialization:{classes:{[qname]:'lazy'}},nativeCallableClasses:{[qname]:source},nativeCallableMetadata:{module:'./AS3MethodBinding',classes:metadata.classes},nativeCallableMethodBindingModule:'./AS3MethodBinding',nativeCallableCoercionModule:'./AS3MethodBinding',nativeCallableStringModule:'./AS3String',nativeArrayCreationModule:'./AS3ArrayCreation',nativeLexicalMembersModule:'./AS3LexicalMembers',nativeTypedLocals:true,nativeTypedLocalAdditionModule:'./AS3Addition'};
const generated=emit(parse('TypedLocals.as',source),source,options),cache=path.join(compiler,'.cache/native-typed-locals');fs.mkdirSync(cache,{recursive:true});const run=fs.mkdtempSync(path.join(cache,'run-'));console.log(run);fs.writeFileSync(path.join(run,'TypedLocals.ts'),generated);
const provider=path.join(run,'engine');fs.mkdirSync(provider);fs.symlinkSync(path.join(engine,'node_modules'),path.join(provider,'node_modules'),'junction');cp.execFileSync('tar',['-xf','-','-C',provider],{input:cp.execFileSync('git',['archive',dependency.engineCommit,'src'],{cwd:engine,maxBuffer:128*1024*1024})});
const committedFileNormalization=[];for(const f of dependency.committedProductionFiles){const file=path.join(provider,f.path),raw=fs.readFileSync(file),normalized=Buffer.from(raw.toString('utf8').replace(/\r\n/g,'\n'),'utf8');assert(raw.equals(Buffer.from(raw.toString('utf8'),'utf8')),'invalid UTF8 engine source');assert.equal(crypto.createHash('sha256').update(normalized).digest('hex'),f.sha256);assert.equal(normalized.length,f.bytes);if(!raw.equals(normalized))committedFileNormalization.push(f.path);}
const names=['AS3MethodBinding','AS3Coercion','AS3String','AS3Type','AS3Property','AS3Class','AS3Invocation','AS3DeclarationType','FlashTypeMetadata','AS3LexicalMembers','AS3ArrayCreation','AS3Addition','QName','AS3DynamicObject'];
const built=esbuild.buildSync({absWorkingDir:provider,stdin:{contents:names.map(n=>'export * from "./src/layaAir/flash/utils/'+n+'";').join('\n'),resolveDir:provider,loader:'ts'},bundle:true,write:false,format:'cjs',platform:'node',target:'es2020',metafile:true});
const graph=Object.keys(built.metafile.inputs).filter(n=>n!=='<stdin>').map(n=>({path:n,sha256:sha(path.resolve(provider,n))}));fs.writeFileSync(path.join(run,'provider-graph.json'),JSON.stringify(graph,null,2));
const utils=path.join(provider,'src/layaAir/flash/utils'),decls=path.join(run,'provider');
const diagnostics=p=>modern.getPreEmitDiagnostics(p).map(d=>({code:d.code,file:d.file?.fileName,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));
const types={target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts']};
const support=modern.sys.readDirectory(path.join(provider,'src/layaAir/tslibs'),['.d.ts']);support.push(...modern.sys.readDirectory(path.join(engine,'node_modules/@webgpu/types'),['.d.ts']),...modern.sys.readDirectory(path.join(engine,'node_modules/minigame-api-typings'),['.d.ts']));const program=modern.createProgram([...names.map(n=>path.join(utils,n+'.ts')),...support],{...types,types:['node'],typeRoots:[path.join(engine,'node_modules/@types')],experimentalDecorators:true,skipLibCheck:true,declaration:true,emitDeclarationOnly:true,rootDir:provider,outDir:decls});fs.writeFileSync(path.join(run,'provider-diagnostics.json'),JSON.stringify(diagnostics(program),null,2));assert.deepEqual(diagnostics(program),[]);assert.equal(program.emit().emitSkipped,false);fs.writeFileSync(path.join(run,'provider-types.json'),JSON.stringify(program.getSourceFiles().map(f=>({path:path.relative(provider,f.fileName),sha256:sha(f.fileName)})),null,2));
(async()=>{const reports=[],browser=await chromium.launch({headless:true});try{for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015]){const dir=path.join(run,'target-'+target);fs.mkdirSync(dir);const specs=[];
function add(name,source,typescript=true){let code=source;if(typescript){const compiled=ts.transpileModule(source,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepEqual(compiled.diagnostics,[]);code=compiled.outputText;}fs.writeFileSync(path.join(dir,name+(typescript?'.ts':'.js')),source);specs.push({name,code});}
add('AS3MethodBinding','(function(){var module={exports:{}};'+built.outputFiles[0].text+';Object.assign(exports,module.exports);})();',false);fs.writeFileSync(path.join(dir,'AS3MethodBinding.d.ts'),names.map(n=>'export * from "../provider/src/layaAir/flash/utils/'+n+'";').join('\n'));
for(const name of ['AS3String','AS3ArrayCreation','AS3LexicalMembers','AS3Addition']){add(name,"Object.assign(exports,require('./AS3MethodBinding'));",false);fs.writeFileSync(path.join(dir,name+'.d.ts'),'export * from "../provider/src/layaAir/flash/utils/'+name+'";');}
for(const name of ['bound','classBound','nativeClass','callableClass'])add(name,read(path.join(compiler,'utils',name+'.ts')));add('TypedLocals',generated);
const errors=diagnostics(modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{...types,experimentalDecorators:true,noEmit:true}));fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(errors,null,2));assert.deepEqual(errors,[]);
const script='{const modules=new Map();const specs='+JSON.stringify(specs)+';for(const s of specs)modules.set(s.name,{});for(const s of specs)new Function("exports","require",s.code)(modules.get(s.name),r=>modules.get(r.split("/").pop()));'+read(path.join(__dirname,'driver.js'))+'}';fs.writeFileSync(path.join(dir,'bundle.js'),script);const context=vm.createContext({performance:require('node:perf_hooks').performance});vm.runInContext(script,context);const node=JSON.parse(JSON.stringify(context.result));fs.writeFileSync(path.join(dir,'node.json'),JSON.stringify(node,null,2));assert.deepEqual(node,expected);
const page=await browser.newPage();await page.addScriptTag({content:script});const web=await page.evaluate(()=>JSON.parse(JSON.stringify(globalThis.result)));await page.close();fs.writeFileSync(path.join(dir,'browser.json'),JSON.stringify(web,null,2));assert.deepEqual(web,expected);reports.push({target,rows:47,node:true,chromium:true,typeDiagnostics:0});
}fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({engineBase:dependency.engineCommit,providerSourceMode:dependency.sourceMode,committedFileNormalization,additionHandoffSHA256:dependency.handoffSHA256,dependencySHA256:sha(dependencyPath),reports,providerSources:graph.length,comparisonNegativeControls:negatives.length,actualProviderTypeFiles:program.getSourceFiles().length,providerGraphSHA256:sha(path.join(run,'provider-graph.json')),generatedSHA256:sha(path.join(run,'TypedLocals.ts'))},null,2));console.log(JSON.stringify({run,reports}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
