const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('node:assert/strict'),crypto=require('crypto');
const {api,options,parse,emit,root,compiler}=require('./emit-domain.cjs'),prior=path.join(root,'retained-research'),metadata=JSON.parse(cp.execFileSync(process.env.PYTHON,[path.join(root,'extract-metadata.py'),path.join(prior,'capture-g')],{encoding:'utf8'}));
const sources=Object.fromEntries(Object.keys(metadata.classes).map(q=>[q,fs.readFileSync(path.join(prior,'capture-g/sources/original',q.replaceAll('.','/')+'.as'),'utf8')]));
const sourceRows=JSON.parse(fs.readFileSync(path.join(prior,'capture-g/flash.json'))),records=[];
function held(id,scope,classes){let error;try{const d=api.createNativeDeclarationDomain({module:'./declarationDomain',sources:scope,metadata:{module:'./AS3MethodBinding',classes},lexicalModule:'./AS3LexicalMembers',typedLocals:true});for(const [q,s]of Object.entries(d.sources))emit(parse(q+'.as',s),s,options(d));}catch(e){error=String(e);}assert(error,'unexpected whole group admission');records.push({id,completeGroup:true,sourceCount:Object.keys(scope).length,metadataCount:Object.keys(classes).length,sources:Object.entries(scope).map(([q,s])=>({qname:q,sha256:crypto.createHash('sha256').update(s).digest('hex')})),error,ready:false});}
assert.equal(Object.keys(sources).length,12);held('original-whole-twelve-class-domain',sources,metadata.classes);assert.match(records[0].error,/Object-root declaration required/);
const maintained=JSON.parse(fs.readFileSync(path.join(prior,'maintained-metadata.json'))),timing=Object.fromEntries(Object.keys(maintained.classes).map(q=>[q,fs.readFileSync(path.join(prior,'maintained-sources',q+'.as'),'utf8')]));
assert.equal(Object.keys(timing).length,5);held('maintained-whole-five-class-timing-domain',timing,maintained.classes);
fs.writeFileSync(path.join(compiler,'.cache/native-foreign-typed-locals/holds.json'),JSON.stringify({originalNominalRows:sourceRows.rows.length,originalInitializationRows:sourceRows.initializationRows.length,originalErrorRows:sourceRows.errorRows.length,originalDomainNativeRowsAdmitted:0,records},null,2));console.log(JSON.stringify(records.map(r=>({id:r.id,sourceCount:r.sourceCount,error:r.error}))));
