'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {domain,input,options,api,parse,emit,root,compiler,writeDomain}=require('./emit-domain.cjs');
const records=[];function check(id,f){f();records.push({id,pass:true});}
const clone=x=>JSON.parse(JSON.stringify(x)),q='domain.a.Node',source=domain.sources[q];
const render=(o=options(),s=source)=>emit(parse(q+'.as',s),s,o),expected=render();
check('public-builder-workflow',()=>assert.equal(typeof api.createNativeDeclarationDomain,'function'));
check('all-five-declarations-single-allocation-module',()=>{assert.equal(domain.bindings.length,5);assert.equal((domain.moduleSource.match(/=declareAS3ReferenceType</g)||[]).length,5);});
check('domain-no-source-class-import-or-read',()=>{assert.equal((domain.moduleSource.match(/^import /gm)||[]).length,1);assert.doesNotMatch(domain.moduleSource,/readNativeClass|declareNativeClass|new |\.Node/);});
check('class-reuses-domain-token',()=>{assert.match(expected,/declarationDomain\.type3/);assert.doesNotMatch(expected,/declareAS3ReferenceType</);});
check('complete-repeat-emission-deterministic',()=>{for(const [name,s]of Object.entries(domain.sources))assert.equal(emit(parse(name+'.as',s),s,options()),emit(parse(name+'.as',s),s,options()));});
check('separate-build-same-names-different-contexts',()=>{const other=api.createNativeDeclarationDomain(input);assert.notEqual(other,domain);assert.notEqual(other.metadata,domain.metadata);assert.equal(other.moduleSource,domain.moduleSource);});
check('caller-source-mutation-cannot-change-plan',()=>{input.sources[q]+=' ';assert.equal(domain.sources[q],source);assert.equal(render(),expected);});
check('caller-metadata-mutation-cannot-change-plan',()=>{input.metadata.classes[q].metadata.name='forged::Node';assert.equal(domain.metadata.classes[q].metadata.name,'domain.a::Node');assert.equal(render(),expected);});
check('frozen-plan-source-write-rejected',()=>assert.throws(()=>domain.sources[q]='forged',TypeError));
check('frozen-plan-nested-metadata-write-rejected',()=>assert.throws(()=>domain.metadata.classes[q].metadata.name='forged',TypeError));
check('frozen-bindings-write-rejected',()=>assert.throws(()=>domain.bindings[0].qname='forged',TypeError));
check('complete-source-byte-drift-rejected',()=>{const o=options();o.nativeCallableClasses={...domain.sources,[q]:source+' '};assert.throws(()=>render(o),/planned source bytes changed/);});
check('missing-source-rejected',()=>{const o=options();o.nativeCallableClasses={...domain.sources};delete o.nativeCallableClasses['domain.Anchor'];assert.throws(()=>render(o),/planned source bytes changed/);});
check('extra-source-rejected',()=>{const o=options();o.nativeCallableClasses={...domain.sources,'foreign.Node':source};assert.throws(()=>render(o),/planned source bytes changed/);});
check('shallow-metadata-copy-rejected',()=>{const o=options();o.nativeCallableMetadata={...domain.metadata};assert.throws(()=>render(o),/missing exact compiler domain capability/);});
check('serialized-options-rejected',()=>assert.throws(()=>render(clone(options())),/missing exact compiler domain capability/));
check('marker-stripped-shallow-table-copy-rejected',()=>{const o=options();o.nativeCallableMetadata={module:domain.metadata.module,classes:domain.metadata.classes};assert.throws(()=>render(o),/missing exact compiler domain capability/);});
check('outer-options-copy-with-exact-capability-supported',()=>assert.equal(render({...options()}),expected));
check('source-table-copy-exact-bytes-supported',()=>{const o=options();o.nativeCallableClasses={...domain.sources};assert.equal(render(o),expected);});
check('changed-lexical-module-rejected',()=>{const o=options();o.nativeLexicalMembersModule='./different';assert.throws(()=>render(o),/domain lexical mode changed/);});
check('changed-typed-local-mode-rejected',()=>{const o=options();o.nativeTypedLocals=false;assert.throws(()=>render(o),/domain lexical mode changed/);});
check('retry-after-rejected-copy-uses-original-context',()=>assert.equal(render(),expected));
const original={module:domain.module,sources:clone(domain.sources),metadata:clone(domain.metadata),lexicalModule:'./AS3LexicalMembers',typedLocals:true};delete original.metadata.nativeDeclarationDomain;
check('explicit-rebuild-after-serialization-supported',()=>{const rebuilt=api.createNativeDeclarationDomain(clone(original));assert.notEqual(rebuilt.metadata,domain.metadata);assert.equal(rebuilt.moduleSource,domain.moduleSource);});
check('rebuild-from-marked-domain-rejected',()=>assert.throws(()=>api.createNativeDeclarationDomain({...original,metadata:domain.metadata}),/original metadata/));
check('metadata-source-sha-drift-rejected',()=>{const bad=clone(original);bad.sources[q]+=' ';assert.throws(()=>api.createNativeDeclarationDomain(bad),/exact authenticated source bytes required/);});
check('metadata-table-extra-rejected',()=>{const bad=clone(original);bad.metadata.classes.extra=bad.metadata.classes[q];assert.throws(()=>api.createNativeDeclarationDomain(bad),/exact complete/);});
check('metadata-accessor-never-invoked',()=>{let seen=0;const bad={...original};Object.defineProperty(bad,'sources',{enumerable:true,get(){seen++;return original.sources;}});assert.throws(()=>api.createNativeDeclarationDomain(bad),/configuration accessors/);assert.equal(seen,0);});
check('cyclic-configuration-rejected-explicitly',()=>{const bad={...original};bad.cycle=bad;assert.throws(()=>api.createNativeDeclarationDomain(bad),/cyclic configuration data/);});
check('domain-provider-module-collision-rejected',()=>assert.throws(()=>api.createNativeDeclarationDomain({...original,module:original.metadata.module}),/cannot replace/));
check('domain-lexical-module-collision-rejected',()=>assert.throws(()=>api.createNativeDeclarationDomain({...original,module:original.lexicalModule}),/cannot replace its lexical provider/));
check('caller-rejects-distinct-domain-at-same-resolved-output',()=>{const outputs=new Map(),file=path.join(compiler,'.cache/native-declaration-domain/output-guard/domain.ts');writeDomain(domain,file,outputs);writeDomain(domain,file,outputs);assert.throws(()=>writeDomain(api.createNativeDeclarationDomain(original),file,outputs),/output already owned/);});
check('caller-allows-distinct-domains-at-distinct-resolved-outputs',()=>{const outputs=new Map(),dir=path.join(compiler,'.cache/native-declaration-domain/output-guard');writeDomain(domain,path.join(dir,'one.ts'),outputs);writeDomain(api.createNativeDeclarationDomain(original),path.join(dir,'two.ts'),outputs);assert.equal(outputs.size,2);});
for(const name of ['Array','Number','String'])check('synthetic-imported-'+name+'-annotation-explicitly-held',()=>{const bad=clone(original);bad.sources[q]=bad.sources[q].replace('import domain.b.Node;','import domain.b.Node; import foreign.'+name+';').replace('this.next=value;return this.next;','var typed:'+name+';this.next=value;return this.next;');bad.metadata.classes[q].sourceSha256=require('crypto').createHash('sha256').update(bad.sources[q]).digest('hex');assert.throws(()=>api.createNativeDeclarationDomain(bad),/imported or same-package builtin-name annotation remains held/);});
check('own-import-name-precedence-retained',()=>assert(domain.references.filter(r=>r.owner===q&&r.sourceName==='Node').every(r=>r.identity===q)));
check('qualified-self-span-and-identity-retained',()=>{const matches=domain.references.filter(r=>r.owner==='domain.b.Node'&&r.sourceName==='domain.b.Node');assert.equal(matches.length,3);for(const r of matches){assert.equal(r.identity,'domain.b.Node');assert.equal(domain.sources[r.owner].slice(r.start,r.end),'domain.b.Node');}});
fs.writeFileSync(path.join(compiler,'.cache/native-declaration-domain/guards.json'),JSON.stringify({compilerBase:'293d1b9ac9f602e67de240116b91a2e8f531e570',records},null,2));console.log(JSON.stringify({guards:records.length}));
