const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('node:assert/strict'),crypto=require('crypto'),vm=require('vm');
const {domain,input,options,api,parse,emit,root,compiler}=require('./emit-domain.cjs');
const engine=process.env.LAYA_ENGINE_REPOSITORY,commit=process.env.DOMAIN_ENGINE_COMMIT||'7ae41d50d43f3288b17873922a903d3f0350a911';
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),esbuild=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const expected=json(path.join(root,'capture-a/flash.json')).rows;assert.deepEqual(json(path.join(root,'capture-b/flash.json')),json(path.join(root,'capture-a/flash.json')));assert.equal(expected.length,16);const negativeControls=[x=>x.pop(),x=>x.reverse(),x=>{x[0].value=false;},x=>{x.find(r=>r.id==='cycle-B-sees-null-A').value=false;}];for(const mutate of negativeControls){const bad=structuredClone(expected);mutate(bad);assert.throws(()=>assert.deepEqual(bad,expected));}
for(const capture of ['capture-a','capture-b'])for(const f of json(path.join(root,capture,'provenance.json')).files){const name=f.path.replaceAll('\\','/');const paths=[path.join(root,capture,'sources',name),path.join(root,capture,name)];assert.equal(sha(paths.find(p=>fs.existsSync(p))),f.sha256);}
const cache=path.join(compiler,'.cache/native-declaration-domain/runs');fs.mkdirSync(cache,{recursive:true});const run=fs.mkdtempSync(path.join(cache,'run-'));console.log(run);
const provider=path.join(run,'engine');fs.mkdirSync(provider);fs.symlinkSync(path.join(engine,'node_modules'),path.join(provider,'node_modules'),'junction');cp.execFileSync('tar',['-xf','-','-C',provider],{input:cp.execFileSync('git',['archive',commit,'src'],{cwd:engine,maxBuffer:128*1024*1024})});
const names=['AS3MethodBinding','AS3Coercion','AS3String','AS3Type','AS3Property','AS3Class','AS3Invocation','AS3DeclarationType','FlashTypeMetadata','AS3LexicalMembers','AS3ArrayCreation','AS3Addition','QName','AS3DynamicObject'];
const built=esbuild.buildSync({absWorkingDir:provider,stdin:{contents:names.map(n=>'export * from "./src/layaAir/flash/utils/'+n+'";').join('\n'),resolveDir:provider,loader:'ts'},bundle:true,write:false,format:'cjs',platform:'node',target:'es2020',metafile:true});
const graph=Object.keys(built.metafile.inputs).filter(n=>n!=='<stdin>').map(n=>({path:n,sha256:sha(path.resolve(provider,n))}));fs.writeFileSync(path.join(run,'provider-graph.json'),JSON.stringify(graph,null,2));
const utils=path.join(provider,'src/layaAir/flash/utils'),decls=path.join(run,'provider');
const diagnostics=p=>modern.getPreEmitDiagnostics(p).map(d=>({code:d.code,file:d.file?.fileName,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));
const types={target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts']};
const support=modern.sys.readDirectory(path.join(provider,'src/layaAir/tslibs'),['.d.ts']);support.push(...modern.sys.readDirectory(path.join(engine,'node_modules/@webgpu/types'),['.d.ts']),...modern.sys.readDirectory(path.join(engine,'node_modules/minigame-api-typings'),['.d.ts']));
const program=modern.createProgram([...names.map(n=>path.join(utils,n+'.ts')),...support],{...types,types:['node'],typeRoots:[path.join(engine,'node_modules/@types')],experimentalDecorators:true,skipLibCheck:true,declaration:true,emitDeclarationOnly:true,rootDir:provider,outDir:decls});fs.writeFileSync(path.join(run,'provider-diagnostics.json'),JSON.stringify(diagnostics(program),null,2));assert.deepEqual(diagnostics(program),[]);assert.equal(program.emit().emitSkipped,false);fs.writeFileSync(path.join(run,'provider-types.json'),JSON.stringify(program.getSourceFiles().map(f=>({path:path.relative(provider,f.fileName),sha256:sha(f.fileName)})),null,2));
const fileFor=q=>q.startsWith('domain.a.')?'a.Node':q.startsWith('domain.b.')?'b.Node':q.split('.').pop();
(async()=>{const reports=[],browser=await chromium.launch({headless:true});try{for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015]){const dir=path.join(run,'target-'+target);fs.mkdirSync(dir);const specs=[];
function add(name,source,typescript=true){let code=source;if(typescript){const compiled=ts.transpileModule(source,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepEqual(compiled.diagnostics,[]);code=compiled.outputText;}fs.writeFileSync(path.join(dir,name+(typescript?'.ts':'.js')),source);specs.push({name,code});}
add('AS3MethodBinding','(function(){var module={exports:{}};'+built.outputFiles[0].text+';Object.assign(exports,module.exports);})();',false);fs.writeFileSync(path.join(dir,'AS3MethodBinding.d.ts'),names.map(n=>'export * from "../provider/src/layaAir/flash/utils/'+n+'";').join('\n'));
for(const name of ['AS3String','AS3ArrayCreation','AS3LexicalMembers','AS3Addition']){add(name,"Object.assign(exports,require('./AS3MethodBinding'));",false);fs.writeFileSync(path.join(dir,name+'.d.ts'),'export * from "../provider/src/layaAir/flash/utils/'+name+'";');}
for(const name of ['bound','classBound','nativeClass','callableClass'])add(name,read(path.join(compiler,'utils',name+'.ts')));
add('declarationDomain',domain.moduleSource);
for(const [q,s] of Object.entries(domain.sources))add(fileFor(q),emit(parse(q+'.as',s),s,options()));
const errors=diagnostics(modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{...types,experimentalDecorators:true,noEmit:true}));fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(errors,null,2));assert.deepEqual(errors,[]);
const script='{const shared=new Map(),specs=new Map('+JSON.stringify(specs)+'.map(s=>[s.name,s.code])),localNames=new Set(["declarationDomain","a.Node","b.Node","Anchor","CycleA","CycleB"]);function createDomainLoader(nativeOverride){const local=new Map();function load(name){if(name==="nativeClass"&&nativeOverride)return nativeOverride;const modules=localNames.has(name)?local:shared;if(modules.has(name))return modules.get(name);if(!specs.has(name))throw Error("unresolved module "+name);const output={};modules.set(name,output);new Function("exports","require",specs.get(name))(output,r=>load(r.split("/").pop()));return output;}load.loaded=local;return load;}const load=createDomainLoader();'+read(path.join(root,'runtime-driver.js'))+'}';fs.writeFileSync(path.join(dir,'bundle.js'),script);
const context=vm.createContext({performance:require('node:perf_hooks').performance});vm.runInContext(script,context);const node=JSON.parse(JSON.stringify(context.result));fs.writeFileSync(path.join(dir,'node.json'),JSON.stringify(node,null,2));
const page=await browser.newPage();await page.addScriptTag({content:script});const web=await page.evaluate(()=>JSON.parse(JSON.stringify(globalThis.result)));await page.close();fs.writeFileSync(path.join(dir,'browser.json'),JSON.stringify(web,null,2));assert.deepEqual(node,web);
const mismatches=expected.filter((r,i)=>r.id!==node.rows[i].id||JSON.stringify(r.value)!==JSON.stringify(node.rows[i].value));fs.writeFileSync(path.join(dir,'mismatches.json'),JSON.stringify(mismatches.map(r=>({expected:r,actual:node.rows.find(x=>x.id===r.id)})),null,2));assert.deepEqual(node.rows,expected);reports.push({target,rows:expected.length-mismatches.length,holds:mismatches.map(r=>r.id),guards:node.guards.length,node:true,chromium:true,typeDiagnostics:0});
}fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({engineCommit:commit,compilerBase:'293d1b9ac9f602e67de240116b91a2e8f531e570',reports,comparisonNegativeControls:negativeControls.length,providerSources:graph.length,actualProviderTypeFiles:program.getSourceFiles().length,providerGraphSHA256:sha(path.join(run,'provider-graph.json'))},null,2));console.log(JSON.stringify({run,reports}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
