const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const model=require('../../lib/emit/native-source-unit'),api=require('../../lib');
const {nativeGeneratedSourceUnit}=require('../../lib/emit/native-generated-declarations');
const engine=path.resolve(process.env.LAYA_ENGINE_REPOSITORY||'../LayaAir-op2'),evidence=path.join(engine,'tests/nativeFlashOracle/file-local-classes');
const rows=require(path.join(evidence,'verify.cjs')),row=id=>rows.find(r=>r.id===id).value;
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const read=q=>{const text=fs.readFileSync(path.join(evidence,'source',q.replaceAll('.','/')+'.as'),'utf8');return model.readNativeSourceUnit(q,text,hash(text));};
const first=read('localcases.First'),second=read('localcases.Second');
assert.deepEqual(first.declarations.map(d=>d.name),['First','Helper','Child']);assert.deepEqual(second.declarations.map(d=>d.name),['Second','Helper']);
const a=first.declarations[1],b=second.declarations[1],child=first.declarations[2];
assert.notEqual(a,b);assert.equal(row('distinct-class'),true);assert.equal(a.reflectedName,row('first-name'));assert.equal(b.reflectedName,row('second-name'));assert.equal(child.reflectedName,row('child-name'));
assert.equal(a.packageQName,null);assert.equal(b.packageQName,null);assert.deepEqual(row('global-lookup'),['ReferenceError',1065]);
assert.deepEqual(row('qualified-lookup'),['ReferenceError',1065]);assert.deepEqual(row('package-lookup'),['ReferenceError',1065]);
for(const d of first.declarations)assert.equal(model.nativeSourceUnitLocal(first,d,'Helper'),a);
assert.equal(model.nativeSourceUnitLocal(second,second.declarations[0],'Helper'),b);
assert.equal(model.nativeSourceUnitLocal(second,second.declarations[0],'Child'),null);
const ast=model.nativeSourceUnitAst(first),body=ast.declarations[1].node;
assert(first.source.slice(body.start,body.end).includes('new Helper(value+1)'));assert.equal(ast.declarations[0].node.parent.parent.kind,require('../../lib/syntax/nodeKind').default.PACKAGE);
body.children.length=0;ast.root.children.length=0;
assert(model.nativeSourceUnitNode(first,a).children.length>0);assert.equal(first.sourceSha256,hash(first.source));
assert(Object.isFrozen(first)&&Object.isFrozen(first.declarations)&&Object.isFrozen(a));
let guards=0;const reject=fn=>{assert.throws(fn,/AS3_SOURCE_UNIT_UNSUPPORTED|AS3_GENERATED_DECLARATIONS_UNSUPPORTED/);guards++;};
reject(()=>model.nativeSourceUnitNode(first,b));reject(()=>model.nativeSourceUnitNode(first,{...a}));
reject(()=>model.nativeSourceUnitLocal(first,second.declarations[0],'Helper'));
reject(()=>model.nativeSourceUnitAst(JSON.parse(JSON.stringify(first))));
reject(()=>model.readNativeSourceUnit(first.owner,first.source+' ',first.sourceSha256));
reject(()=>model.readNativeSourceUnit('localcases.Other',first.source,first.sourceSha256));
const duplicate=first.source+'\nclass Helper {}';reject(()=>model.readNativeSourceUnit(first.owner,duplicate,hash(duplicate)));
const simple='package sample {public class Single {public var value:int;}}',plan=api.createNativeGeneratedDeclarationPlan({scope:'source-unit-regression',providerModule:'./provider',sources:{'sample.Single':{source:simple,sourceSha256:hash(simple)}}});
const retained=nativeGeneratedSourceUnit(plan,'sample.Single');assert.equal(retained.source,simple);assert.equal(retained.declarations[0].packageQName,'sample.Single');
reject(()=>nativeGeneratedSourceUnit(JSON.parse(JSON.stringify(plan)),'sample.Single'));
// Recognition is deliberately not admission before multi-declaration emitters exist.
reject(()=>api.createNativeGeneratedDeclarationPlan({scope:'file-local-pending',providerModule:'./provider',sources:{[first.owner]:{source:first.source,sourceSha256:first.sourceSha256}}}));
console.log(JSON.stringify({qualification:'source-unit identity model and existing single-declaration planner integration; no native runtime replay',flashRows:rows.length,sourceFiles:2,privateDeclarations:3,guards}));
