const P=modules.get('AS3MethodBinding'),read=modules.get('nativeClass').readNativeClass;
const C=read(modules.get('LexicalUnit').LexicalUnit),x=P.as3ConstructValue(C,()=>[]),y=P.as3ConstructValue(C,()=>[]);
const call=(receiver,key,...args)=>P.as3CallProperty(receiver,key,()=>args),invoke=(fn,...args)=>P.as3CallValue(fn,()=>args),get=P.as3GetProperty;
let events=[],rows=[];
function rec(id,fn){events=[];try{rows.push({id,value:fn(),events:events.slice()})}catch(e){rows.push({id,error:{name:e.name,errorID:e.errorID},events:events.slice()})}}
rec('defaults',()=>[call(x,'read'),call(x,'invoke',2),call(C,'staticRead'),call(x,'arrayRead'),get(x,'publicValue')]);
rec('array-fresh',()=>call(x,'arrayIdentity')!==call(y,'arrayIdentity'));
rec('field-write',()=>[call(x,'write','7'),call(x,'read')]);
rec('protected-write',()=>call(x,'invoke','8'));
rec('implicit',()=>call(x,'implicit'));
rec('closure-stable',()=>[call(x,'closure')===call(x,'closure'),call(x,'closure')!==call(y,'closure'),invoke(call(x,'closure'))]);
rec('closure-receiver',()=>{const f=call(x,'closure');return [call(f,'call',y),call(f,'apply',null,P.as3CreateArrayLiteral([])),get(f,'length')]});
rec('protected-closure',()=>{const f=call(x,'protectedClosure');return [invoke(f,'11'),get(f,'length')]});
rec('static-closure',()=>{const f=call(C,'callback');return [invoke(f,'12'),call(C,'staticRead'),f===call(C,'callback'),get(f,'length')]});
rec('parameter-shadow',()=>call(x,'parameterShadow','parameter'));
rec('local-shadow',()=>call(x,'localShadow'));
rec('catch-shadow',()=>call(x,'catchShadow'));
rec('catch-after',()=>call(x,'catchAfter'));
rec('dynamic-private',()=>call(x,'dynamicRead','secret'));
rec('dynamic-write',()=>[call(x,'dynamicWrite','secret','13'),call(x,'read')]);
rec('dynamic-call',()=>call(x,'dynamicCall','secretMethod'));
rec('dynamic-public',()=>call(x,'dynamicRead','publicValue'));
rec('public-qname-private',()=>call(x,'dynamicRead',new P.QName('','secret')));
rec('external-private',()=>get(x,'secret'));
rec('private-arity-extra',()=>invoke(call(x,'closure'),1));
rec('protected-arity-missing',()=>invoke(call(x,'protectedClosure')));
rec('protected-arity-extra',()=>invoke(call(x,'protectedClosure'),1,2));
rec('static-arity-missing',()=>invoke(call(C,'callback')));
rec('coercion-order',()=>{const hook=P.as3CreateDynamicObject();P.as3SetProperty(hook,'valueOf',function(){events.push('valueOf');return 14});return [call(x,'write',hook),call(x,'read')]});
globalThis.result=rows;
globalThis.storageGuards={ownNames:Object.getOwnPropertyNames(x),prototypeNames:Object.getOwnPropertyNames(C.prototype),staticNames:Object.getOwnPropertyNames(C),prototypeSymbols:Object.getOwnPropertySymbols(C.prototype).length,entered:P.getAS3EnteredSourceConstructors(x).length};
