const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto'),assert=require('node:assert/strict'),vm=require('vm');
const compiler=path.resolve(__dirname,'../..'),engine=process.env.LAYA_ENGINE_REPOSITORY||path.resolve(compiler,'../LayaAir-op2');
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),esbuild=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||require.resolve('playwright',{paths:[compiler,engine]}));
const parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit'));
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
cp.execFileSync(process.env.PYTHON||'python',[path.join(__dirname,'verify-evidence.py')],{encoding:'utf8',windowsHide:true});
const order=process.argv.includes('--order'),className=order?'LexicalOrder':'LexicalUnit';
const evidence=path.join(__dirname,order?'order-evidence':'unit-evidence'),receipt=path.join(evidence,'provenance.json');assert.equal(sha(receipt),order?'37aaf106705973605f6343db0bccf9bb273f183df4909329ff7b0fc7419eab6e':'9cb17b88c072f19ad2479b9e42834ec7a6afb727f70ab3bc55321aab0476a589');
for(const f of json(receipt).files){const p=fs.existsSync(path.join(evidence,f.path))?path.join(evidence,f.path):path.join(evidence,'sources',f.path);assert.equal(sha(p),f.sha256,f.path);}
const expected=json(path.join(evidence,'flash.json')).rows;assert.equal(expected.length,order?8:24);
const cache=path.join(compiler,'.cache/native-lexical-members');fs.mkdirSync(cache,{recursive:true});const run=fs.mkdtempSync(path.join(cache,'run-'));console.log(run);
const metadata=JSON.parse(cp.execFileSync(process.env.PYTHON||'python',[path.join(__dirname,'extract-metadata.py'),evidence],{encoding:'utf8',windowsHide:true}));
const source=read(path.join(evidence,'sources/original/probe/'+className+'.as')),qname='probe.'+className;
const options={customVisitors:[],definitionsByNamespace:{probe:[className]},nativeClassInitialization:{classes:{[qname]:'lazy'}},nativeCallableClasses:{[qname]:source},nativeCallableMetadata:{module:'./AS3MethodBinding',classes:metadata.classes},nativeCallableMethodBindingModule:'./AS3MethodBinding',nativeCallableCoercionModule:'./AS3MethodBinding',nativeCallableStringModule:'./AS3String',nativeArrayCreationModule:'./AS3ArrayCreation',nativeLexicalMembersModule:'./AS3LexicalMembers'};
const generated=emit(parse(className+'.as',source),source,options);fs.writeFileSync(path.join(run,className+'.ts'),generated);
const provider=path.join(run,'engine');fs.mkdirSync(provider);cp.execFileSync('tar',['-xf','-','-C',provider],{input:cp.execFileSync('git',['archive','9fd3c0ab0480e09907da5974c484a1db3875570e','src/layaAir/flash/utils'],{cwd:engine,maxBuffer:32*1024*1024})});
const exports_=['AS3MethodBinding','AS3Coercion','AS3String','AS3Type','AS3Property','AS3Class','AS3Invocation','AS3DeclarationType','FlashTypeMetadata','AS3LexicalMembers','AS3ArrayCreation','QName','AS3DynamicObject'];
const built=esbuild.buildSync({absWorkingDir:provider,stdin:{contents:exports_.map(n=>'export * from "./src/layaAir/flash/utils/'+n+'";').join('\n'),resolveDir:provider,loader:'ts'},bundle:true,write:false,format:'cjs',platform:'node',target:'es2020',metafile:true});
const graph=Object.keys(built.metafile.inputs).filter(n=>n!=='<stdin>').map(n=>{const file=path.resolve(provider,n);return {path:path.relative(provider,file).replace(/\\/g,'/'),sha256:sha(file)}});fs.writeFileSync(path.join(run,'provider-graph.json'),JSON.stringify(graph,null,2));
const utils=path.join(provider,'src/layaAir/flash/utils'),declarations=path.join(run,'provider');
const diagnostic=p=>modern.getPreEmitDiagnostics(p).map(d=>({file:d.file?.fileName,code:d.code,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));
const typeOptions={target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts']};
const p=modern.createProgram(exports_.map(n=>path.join(utils,n+'.ts')),{...typeOptions,declaration:true,emitDeclarationOnly:true,rootDir:utils,outDir:declarations});assert.deepEqual(diagnostic(p),[]);assert.equal(p.emit().emitSkipped,false);const typeGraph=p.getSourceFiles().map(f=>({path:path.relative(provider,f.fileName).replace(/\\/g,'/'),sha256:sha(f.fileName)}));fs.writeFileSync(path.join(run,'provider-type-graph.json'),JSON.stringify(typeGraph,null,2));
(async()=>{const reports=[],browser=await chromium.launch({headless:true});try{for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015]){
 const dir=path.join(run,'target-'+target);fs.mkdirSync(dir);const specs=[];
 function add(name,source,typescript=true){let code=source;if(typescript){const r=ts.transpileModule(source,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepEqual(r.diagnostics,[]);code=r.outputText;}fs.writeFileSync(path.join(dir,name+(typescript?'.ts':'.js')),source);specs.push({name,code});}
 add('AS3MethodBinding','(function(){var module={exports:{}};'+built.outputFiles[0].text+';Object.assign(exports,module.exports);})();',false);
 fs.writeFileSync(path.join(dir,'AS3MethodBinding.d.ts'),exports_.map(n=>'export * from "../provider/'+n+'";').join('\n'));
 for(const name of ['AS3String','AS3ArrayCreation','AS3LexicalMembers']){add(name,"Object.assign(exports,require('./AS3MethodBinding'));",false);fs.writeFileSync(path.join(dir,name+'.d.ts'),'export * from "../provider/'+name+'";');}
 for(const name of ['bound','classBound','nativeClass','callableClass'])add(name,read(path.join(compiler,'utils',name+'.ts')));
 add(className,generated);
 const errors=diagnostic(modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{...typeOptions,experimentalDecorators:true,noEmit:true}));fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(errors,null,2));assert.deepEqual(errors,[]);
 const script='{const modules=new Map();const specs='+JSON.stringify(specs)+';for(const spec of specs)modules.set(spec.name,{});for(const spec of specs)new Function("exports","require",spec.code)(modules.get(spec.name),request=>modules.get(request.split("/").pop()));'+read(path.join(__dirname,order?'order-driver.js':'driver.js'))+'}';fs.writeFileSync(path.join(dir,'bundle.js'),script);
 const context=vm.createContext({});vm.runInContext(script,context);const node=JSON.parse(JSON.stringify(context.result));fs.writeFileSync(path.join(dir,'node.json'),JSON.stringify(node,null,2));assert.deepEqual(node,expected);
 const page=await browser.newPage();await page.addScriptTag({content:script});const web=await page.evaluate(()=>JSON.parse(JSON.stringify(globalThis.result)));fs.writeFileSync(path.join(dir,'browser.json'),JSON.stringify(web,null,2));assert.deepEqual(web,expected);assert.deepEqual(await page.evaluate(()=>globalThis.storageGuards),JSON.parse(JSON.stringify(context.storageGuards)));await page.close();
 const guards=JSON.parse(JSON.stringify(context.storageGuards));assert(!guards.ownNames.includes('secret'));assert(!guards.prototypeNames.includes('secretMethod'));assert(!guards.staticNames.includes('token'));assert(!guards.staticNames.includes('event'));assert.equal(guards.prototypeSymbols,order?4:2);assert.equal(guards.entered,1);reports.push({target,rows:node.length,guards,types:0,node:true,chromium:true});
 }fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({engine:'9fd3c0ab0480e09907da5974c484a1db3875570e',reports,providerGraphSHA256:sha(path.join(run,'provider-graph.json')),providerSourceCount:graph.length,providerTypeSourceCount:typeGraph.length,providerTypeGraphSHA256:sha(path.join(run,'provider-type-graph.json')),originalReceiptSHA256:sha(receipt),generatedSHA256:sha(path.join(run,className+'.ts'))},null,2));console.log(JSON.stringify({run,reports}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
