const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),root=path.resolve(__dirname,'../..'),pin=require('./runtime-pin.json'),bytes=fs.readFileSync(path.join(__dirname,'runtime.json.gz'));assert.equal(hash(bytes),pin.sha256);assert.equal(bytes.length,pin.bytes);
const archive=JSON.parse(zlib.gunzipSync(bytes)),files=new Map(archive.files.map(i=>[i.file,i]));assert.equal(files.size,pin.files);
for(const item of files.values()){assert.equal(hash(Buffer.from(item.base64,'base64')),item.sha256);if(process.argv.includes('--check-current'))assert.equal(hash(fs.readFileSync(item.file)),item.sha256,item.file);}
const read=file=>{assert.ok(files.has(file),file);return Buffer.from(files.get(file).base64,'base64');},json=file=>JSON.parse(read(file));
function inspect(value,name){if(!value||typeof value!=='object')return;if(typeof value.file==='string'&&typeof value.sha256==='string')assert.equal(hash(read(archive.references[name+'|'+value.file])),value.sha256);for(const item of Object.values(value))inspect(item,name);}
for(const [name,report]of Object.entries(archive.reports))inspect(report,name);
const receipt=json(path.join(archive.oracle,'evidence/receipt.json'));assert.equal(receipt.status,'passed');assert.equal(receipt.capture.identical,true);assert.equal(receipt.capture.runs,2);
for(const [file,digest]of Object.entries(receipt.artifacts))assert.equal(hash(read(path.join(archive.oracle,'evidence',file))),digest);
for(const row of archive.oracleInputs){assert.equal(hash(read(row.file)),row.sha256);assert.equal(receipt.inputs[row.file],row.sha256);}
const a=json(path.join(archive.oracle,'evidence/run-1/capture.json')),b=json(path.join(archive.oracle,'evidence/run-2/capture.json')),expected=json(path.join(archive.oracle,'expected.json'));assert.deepEqual(a,b);assert.deepEqual(a.state.observations,expected);assert.equal(expected.length,17);
const primary=archive.reports.primary;assert.deepEqual(primary.results.map(r=>r.target),['ES5','ES2015']);
for(const [q,source]of Object.entries(primary.cohorts.parent)){assert.equal(hash(source.source),source.sourceSha256);assert.equal(hash(read(path.join(archive.oracle,'source',q.replaceAll('.','/')+'.as'))),source.sourceSha256);}
assert.equal(hash(read(path.join(__dirname,'run.cjs'))),primary.runnerSha256);assert.equal(hash(read(path.join(__dirname,'observer.ts'))),primary.observerSha256);
for(const result of primary.results){assert.deepEqual(result.node,result.web);assert.deepEqual(result.node.rows,expected);assert.equal(result.node.domainChecks.length,5);assert.ok(result.node.domainChecks.every(Boolean));assert.deepEqual(result.typechecks.flatMap(t=>t.diagnostics),[]);assert.ok(result.typechecks.some(t=>t.cohort==='observer'));assert.equal(result.rejectionGuards,2);assert.equal(result.mutations,1);assert.deepEqual(result.control.node,result.control.web);assert.notDeepEqual(result.control.node.rows,expected);assert.deepEqual(result.control.mismatches,['accessor','replace-callback','null-0','null-2','getter-failure-0','getter-failure-1','argument-throws-before-null']);}
for(const result of archive.reports.accessors.runs){assert.deepEqual(result.actual.node,result.actual.web);assert.equal(result.actual.node.rows.length,14);assert.deepEqual(result.typecheck.diagnostics,[]);assert.equal(result.guards.length,10);assert.equal(result.controls.length,2);}
for(const result of archive.reports.objectCalls.results){assert.deepEqual(result.node,result.web);assert.equal(result.node.rows.length,12);assert.deepEqual(result.typechecks.flatMap(t=>t.diagnostics),[]);assert.equal(result.mutations,1);}
const lexical=archive.reports.lexical;assert.deepEqual(lexical.typecheck.diagnostics,[]);assert.equal(lexical.rejectionGuards,7);assert.equal(lexical.comparisonNegativeControls,5);for(const result of lexical.results){assert.deepEqual(result.node,result.web);assert.equal(result.node.length,38);}
if(process.argv.includes('--check-index')||process.argv.includes('--check-git')){const index=process.argv.includes('--check-index');for(const item of primary.compilerInputs){const relative=path.relative(root,item.file).replaceAll('\\','/'),tracked=cp.execFileSync('git',['show',(index?':':'HEAD:')+relative],{cwd:root,maxBuffer:64*1024*1024});if(relative==='src/emit/native-generated-lexical.ts')assert.equal(hash(tracked),item.sha256);else assert.equal(tracked.toString().replace(/\r\n/g,'\n'),read(item.file).toString().replace(/\r\n/g,'\n'));}}
console.log(JSON.stringify({status:'passed',AIRRows:17,adjacentRows:64,targets:2,realms:2,guards:2,domainChecks:5,appliedControls:1,wholeClientQualified:false}));module.exports=archive;
