const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('node:assert/strict'),crypto=require('crypto'),vm=require('vm');
const compiler=path.resolve(__dirname,'../..'),engine=process.env.LAYA_ENGINE_REPOSITORY;
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),esbuild=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE),parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit'));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p));
assert.equal(sha(path.join(__dirname,'files.json')),'db0de13bfb6c1ca3552ce2183ec8be33388218d9e9effda1d290b19d1903f5d8');
const fixture=process.argv[2];assert(['retained76','expressions14','collision'].includes(fixture),'Unknown fixture');const fixtureRoot=path.join(__dirname,'fixtures',fixture);
for(const f of json(path.join(__dirname,'files.json')))assert.equal(sha(path.join(__dirname,f.path)),f.sha256,f.path);
const evidence=path.join(fixtureRoot,'capture-c'),expected=json(path.join(evidence,'flash.json')).rows;assert.equal(expected.length,fixture==='retained76'?76:fixture==='expressions14'?14:6);assert.deepEqual(json(path.join(fixtureRoot,'capture-d/flash.json')).rows,expected);const negatives=[x=>x.pop(),x=>{x[0].id='wrong';},x=>{x[0].extra=true;},x=>{const row=x.find(r=>r.events);if(row)row.events.push('unexpected');else x[0].value='wrong';}];for(const mutate of negatives){const wrong=structuredClone(expected);mutate(wrong);assert.throws(()=>assert.deepEqual(wrong,expected));}
const dependency={engineCommit:'4c3eaf32cefc654e8b086036705c5576b9b4edf4',sourceMode:'committed-engine'};
assert.equal(cp.execFileSync('git',['rev-parse',dependency.engineCommit+'^{commit}'],{cwd:engine,encoding:'utf8',windowsHide:true}).trim(),dependency.engineCommit);
const source=read(path.join(evidence,'sources/original/probe/RelationalReview.as')),qname='probe.RelationalReview';
const metadata=JSON.parse(cp.execFileSync(process.env.PYTHON,[path.join(__dirname,'extract-metadata.py'),evidence],{encoding:'utf8',windowsHide:true}));
const options={customVisitors:[],definitionsByNamespace:{probe:['RelationalReview']},nativeClassInitialization:{classes:{[qname]:'lazy'}},nativeCallableClasses:{[qname]:source},nativeCallableMetadata:{module:'./AS3MethodBinding',classes:metadata.classes},nativeCallableMethodBindingModule:'./AS3MethodBinding',nativeCallableCoercionModule:'./AS3MethodBinding',nativeCallableStringModule:'./AS3String',nativeArrayCreationModule:'./AS3ArrayCreation',nativeLexicalMembersModule:'./AS3LexicalMembers',nativeTypedLocals:true,nativeRelationalModule:'./AS3Relational',nativeTypedLocalAdditionModule:'./AS3Addition'};
const generated=emit(parse('RelationalReview.as',source),source,options),cache=path.join(compiler,'.cache/native-relational',fixture);fs.mkdirSync(cache,{recursive:true});const run=fs.mkdtempSync(path.join(cache,'run-'));console.log(run);fs.writeFileSync(path.join(run,'RelationalReview.ts'),generated);
const provider=path.join(run,'engine');fs.mkdirSync(provider);fs.symlinkSync(path.join(engine,'node_modules'),path.join(provider,'node_modules'),'junction');cp.execFileSync('tar',['-xf','-','-C',provider],{input:cp.execFileSync('git',['archive',dependency.engineCommit,'src'],{cwd:engine,maxBuffer:128*1024*1024})});
const names=['AS3MethodBinding','AS3Coercion','AS3String','AS3Type','AS3Property','AS3Class','AS3Invocation','AS3DeclarationType','FlashTypeMetadata','AS3LexicalMembers','AS3ArrayCreation','AS3Addition','AS3Relational','XML','QName','AS3DynamicObject'];
const built=esbuild.buildSync({absWorkingDir:provider,stdin:{contents:names.map(n=>'export * from "./src/layaAir/flash/utils/'+n+'";').join('\n'),resolveDir:provider,loader:'ts'},bundle:true,write:false,format:'cjs',platform:'node',target:'es2020',metafile:true});
const graph=Object.keys(built.metafile.inputs).filter(n=>n!=='<stdin>').map(n=>({path:n,sha256:sha(path.resolve(provider,n))}));fs.writeFileSync(path.join(run,'provider-graph.json'),JSON.stringify(graph,null,2));
const utils=path.join(provider,'src/layaAir/flash/utils'),decls=path.join(run,'provider');
const diagnostics=p=>modern.getPreEmitDiagnostics(p).map(d=>({code:d.code,file:d.file?.fileName,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));
const types={target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts']};
const support=modern.sys.readDirectory(path.join(provider,'src/layaAir/tslibs'),['.d.ts']);support.push(...modern.sys.readDirectory(path.join(engine,'node_modules/@webgpu/types'),['.d.ts']),...modern.sys.readDirectory(path.join(engine,'node_modules/minigame-api-typings'),['.d.ts']));const program=modern.createProgram([...names.map(n=>path.join(utils,n+'.ts')),...support],{...types,types:['node'],typeRoots:[path.join(engine,'node_modules/@types')],experimentalDecorators:true,skipLibCheck:true,declaration:true,emitDeclarationOnly:true,rootDir:provider,outDir:decls});fs.writeFileSync(path.join(run,'provider-diagnostics.json'),JSON.stringify(diagnostics(program),null,2));assert.deepEqual(diagnostics(program),[]);assert.equal(program.emit().emitSkipped,false);fs.writeFileSync(path.join(run,'provider-types.json'),JSON.stringify(program.getSourceFiles().map(f=>({path:path.relative(provider,f.fileName),sha256:sha(f.fileName)})),null,2));
(async()=>{const reports=[],browser=await chromium.launch({headless:true});try{for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015]){const dir=path.join(run,'target-'+target);fs.mkdirSync(dir);const specs=[];
function add(name,source,typescript=true){let code=source;if(typescript){const compiled=ts.transpileModule(source,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepEqual(compiled.diagnostics,[]);code=compiled.outputText;}fs.writeFileSync(path.join(dir,name+(typescript?'.ts':'.js')),source);specs.push({name,code});}
add('AS3MethodBinding','(function(){var module={exports:{}};'+built.outputFiles[0].text+';Object.assign(exports,module.exports);})();',false);fs.writeFileSync(path.join(dir,'AS3MethodBinding.d.ts'),names.map(n=>'export * from "../provider/src/layaAir/flash/utils/'+n+'";').join('\n'));
for(const name of ['AS3String','AS3ArrayCreation','AS3LexicalMembers','AS3Addition','AS3Relational']){add(name,"Object.assign(exports,require('./AS3MethodBinding'));",false);fs.writeFileSync(path.join(dir,name+'.d.ts'),'export * from "../provider/src/layaAir/flash/utils/'+name+'";');}
for(const name of ['bound','classBound','nativeClass','callableClass'])add(name,read(path.join(compiler,'utils',name+'.ts')));add('RelationalReview',generated);
const errors=diagnostics(modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{...types,experimentalDecorators:true,noEmit:true}));fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(errors,null,2));assert.deepEqual(errors,[]);
const script='{const modules=new Map();const specs='+JSON.stringify(specs)+';for(const s of specs)modules.set(s.name,{});for(const s of specs)new Function("exports","require",s.code)(modules.get(s.name),r=>modules.get(r.split("/").pop()));'+read(path.join(fixtureRoot,'driver.js'))+(fixture==='retained76'?read(path.join(__dirname,'domain-guards.js')):'')+'}';fs.writeFileSync(path.join(dir,'bundle.js'),script);const context=vm.createContext({performance:require('node:perf_hooks').performance});vm.runInContext(script,context);const node=JSON.parse(JSON.stringify(context.result));fs.writeFileSync(path.join(dir,'node.json'),JSON.stringify(node,null,2));assert.equal(node.length,expected.length);const domain=fixture==='retained76'?JSON.parse(JSON.stringify(context.domainGuards)):[];assert.equal(domain.length,fixture==='retained76'?56:0);assert(domain.every(x=>x.held&&x.effects===0));fs.writeFileSync(path.join(dir,'domain-guards.json'),JSON.stringify(domain,null,2));
const page=await browser.newPage();await page.addScriptTag({content:script});const web=await page.evaluate(()=>JSON.parse(JSON.stringify(globalThis.result)));const browserDomain=fixture==='retained76'?await page.evaluate(()=>JSON.parse(JSON.stringify(globalThis.domainGuards))):[];assert.deepEqual(browserDomain,domain);await page.close();fs.writeFileSync(path.join(dir,'browser.json'),JSON.stringify(web,null,2));assert.deepEqual(web,node);const differences=expected.flatMap((original,i)=>{try{assert.deepEqual(node[i],original);return [];}catch{return [{index:i,original,native:node[i]}];}});fs.writeFileSync(path.join(dir,"differences.json"),JSON.stringify(differences,null,2));assert.deepEqual(differences,[]);reports.push({target,rows:expected.length,matches:expected.length,mismatches:0,nodeChromiumEqual:true,typeDiagnostics:0});
}fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({engineBase:dependency.engineCommit,providerSourceMode:dependency.sourceMode,reports,providerSources:graph.length,comparisonNegativeControls:negatives.length,domainGuards:fixture==='retained76'?56:0,actualProviderTypeFiles:program.getSourceFiles().length,providerGraphSHA256:sha(path.join(run,'provider-graph.json')),generatedSHA256:sha(path.join(run,'RelationalReview.ts'))},null,2));console.log(JSON.stringify({run,reports}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
