const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),cp=require('child_process'),crypto=require('crypto'),vm=require('vm');
// node import-run.cjs BASE_SELF_RUN [COMPILER] [EVIDENCE]; outputs stay in BASE_SELF_RUN/imports.
const compiler=path.resolve(process.argv[3]||path.join(__dirname,'../..')),run=path.resolve(process.argv[2]),evidenceRoot=path.resolve(process.argv[4]||path.join(__dirname,'import-evidence'));
const engine=process.env.LAYA_ENGINE_REPOSITORY||path.resolve(compiler,'../LayaAir-op2');
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit'));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p));
const pins={"explicit-foreign-own-Node": "9ae08dd40fd50d6d15d0531e1726f9643f2e3a90162b4e15db6f6b80b3b3b7f6", "explicit-foreign-String": "1110e5f1d30dbe4b512eaff9a0537053aec238bdbc891f622dc21165f95adbff", "wildcard-foreign-String": "f721c06a984c7b5b22582274347300d239a73b45b71e04661dc79a365e9f170e", "wildcard-own-Node": "989eebc8d8a46139b687b551f9470e77d6a31e86b904bcc731cc507d43f38b38"};
const out=path.join(run,'imports');fs.mkdirSync(out,{recursive:true});fs.cpSync(path.join(run,'provider'),path.join(out,'provider'),{recursive:true});
const records=[];for(const [label,receiptHash] of Object.entries(pins)){let evidence=path.join(evidenceRoot,label);if(fs.existsSync(path.join(evidence,'flash')))evidence=path.join(evidence,'flash');assert.equal(sha(path.join(evidence,'provenance.json')),receiptHash);for(const f of json(path.join(evidence,'provenance.json')).files){const rel=f.path.replaceAll('\\','/'),p=fs.existsSync(path.join(evidence,rel))?path.join(evidence,rel):path.join(evidence,'sources',rel);assert.equal(sha(p),f.sha256,rel);}const name=label.includes('Node')?'Node':'Holder',qname='probe.'+name,source=read(path.join(evidence,'sources/original/probe',name+'.as'));const metadata=JSON.parse(cp.execFileSync(process.env.PYTHON||'python',[path.join(compiler,'tests/native-self-constructors/extract-metadata.py'),evidence],{encoding:'utf8',windowsHide:true}));const options={customVisitors:[],definitionsByNamespace:{probe:[name],foreign:['Node','String']},nativeClassInitialization:{classes:{[qname]:'lazy'}},nativeCallableClasses:{[qname]:source},nativeCallableMethodBindingModule:'./AS3MethodBinding',nativeCallableCoercionModule:'./AS3MethodBinding',nativeCallableStringModule:'./AS3String',nativeCallableMetadata:{module:'./AS3MethodBinding',classes:metadata.classes}};records.push({label,name,evidence,source,output:emit(parse(name+'.as',source),source,options),expected:json(path.join(evidence,'flash.json')).rows,receiptHash});}
assert.equal(records.reduce((n,r)=>n+r.expected.length,0),16);
const foreign=path.join(out,'foreign');fs.mkdirSync(foreign,{recursive:true});for(const name of ['Node','String']){const source=read(path.join(records[0].evidence,'sources/original/foreign',name+'.as'));const output=emit(parse(name+'.as',source),source,{customVisitors:[],definitionsByNamespace:{foreign:['Node','String']},nativeClassInitialization:{classes:{['foreign.'+name]:'lazy'}}});fs.writeFileSync(path.join(foreign,name+'.ts'),output);}for(const helper of ['bound','classBound','nativeClass'])fs.copyFileSync(path.join(run,'target-1',helper+'.ts'),path.join(foreign,helper+'.ts'));
(async()=>{const browser=await chromium.launch({headless:true}),reports=[];try{for(const target of [1,2]){let bundle=read(path.join(run,'target-'+target,'bundle.js'));assert(bundle.endsWith('}'));let extra='globalThis.importRows={};';const declarations=[];
for(const r of records){const dir=path.join(out,'target-'+target+'-'+r.label);fs.mkdirSync(dir,{recursive:true});for(const f of ['AS3MethodBinding.d.ts','AS3MethodBinding.js','AS3String.d.ts','AS3String.js','bound.ts','classBound.ts','callableClass.ts','nativeClass.ts'])fs.copyFileSync(path.join(run,'target-'+target,f),path.join(dir,f));fs.writeFileSync(path.join(dir,r.name+'.ts'),r.output);const program=modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts'],experimentalDecorators:true,noEmit:true});const diagnostics=modern.getPreEmitDiagnostics(program).map(d=>({code:d.code,file:d.file?.fileName,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(diagnostics,null,2));assert.deepEqual(diagnostics,[]);declarations.push({label:r.label,diagnostics});const compiled=ts.transpileModule(r.output,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepEqual(compiled.diagnostics,[]);extra+='{const exports={};new Function("exports","require",'+JSON.stringify(compiled.outputText)+')(exports,r=>modules.get(r.split("/").pop()));const S=modules.get("nativeClass").readNativeClass(exports.'+r.name+'),v=new S(),rows=[];function row(id,f){try{rows.push({id,value:f()});}catch(e){rows.push({id,error:e.errorID,name:e.name});}}';if(r.name==='Node')extra+='row("default-null",()=>v.next===null);row("valid-self",()=>new S(v).next===v);row("wrong-plain",()=>new S({}).next);';else extra+='row("omitted-null",()=>v.next===null);row("null-null",()=>new S(null).next===null);row("undefined-null",()=>new S(undefined).next===null);row("numeric-string",()=>new S(12).next);row("object-string-hook",()=>{let calls=0;const input={toString(){calls++;return "hook-result";}};return [new S(input).next,calls];});';extra+='globalThis.importRows['+JSON.stringify(r.label)+']=rows;}';}
bundle=bundle.slice(0,-1)+extra+'}';const file=path.join(out,'runtime-'+target+'.js');fs.writeFileSync(file,bundle);const ctx=vm.createContext({});vm.runInContext(bundle,ctx);const node=JSON.parse(JSON.stringify(ctx.importRows)),page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.addScriptTag({content:bundle});const web=await page.evaluate(()=>globalThis.importRows);await page.close();for(const r of records){assert.deepEqual(node[r.label],r.expected);assert.deepEqual(web[r.label],r.expected);}assert.deepEqual(errors,[]);reports.push({target,node,chromium:web,declarations,bundleSHA256:sha(file)});}const report={originalRows:16,receipts:pins,scope:'Own Class and builtin String type annotation precedence over imports; actual emitted foreign declarations included; no general foreign Class binding admission',reports};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({originalRows:16,node:true,chromium:true,actualDeclarationDiagnostics:0,report:path.join(out,'report.json')}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
