const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),cp=require('child_process'),crypto=require('crypto'),vm=require('vm');
const compiler=path.resolve(__dirname,'../..'),engine=process.env.LAYA_ENGINE_REPOSITORY||path.resolve(compiler,'../LayaAir-op2');
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),esbuild=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||require.resolve('playwright',{paths:[compiler,engine]}));const parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit'));
const pin='69789c4fa64dec426cf86a0ecd4cccfedf79be6c',read=p=>fs.readFileSync(p,'utf8'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),json=p=>JSON.parse(read(p));
const evidence=path.join(__dirname,'evidence'),receiptPath=path.join(evidence,'provenance.json');
const expectedReceipt='8a51d3524539bcc3c4b4aa23c1613c26ec03044986fa3c6c6d3ace5ff609cd33';assert.equal(sha(receiptPath),expectedReceipt);
for(const item of json(receiptPath).files){const rel=item.path.replace(/\\/g,'/'),p=fs.existsSync(path.join(evidence,rel))?path.join(evidence,rel):path.join(evidence,'sources',rel);assert.equal(sha(p),item.sha256,rel);}
const all=json(path.join(evidence,'flash.json')).rows;assert.equal(all.length,32);const expected=all.filter(x=>x.id.startsWith('actual-'));assert.equal(expected.length,8);
const cache=path.join(compiler,'.cache/native-self-constructors');fs.mkdirSync(cache,{recursive:true});const run=fs.mkdtempSync(path.join(cache,'run-'));console.log('Evidence: '+run);
function diagnostics(program){return modern.getPreEmitDiagnostics(program).map(d=>({code:d.code,file:d.file?.fileName,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));}
(async()=>{
 const providerSource=path.join(run,'engine');fs.mkdirSync(providerSource);const archive=cp.execFileSync('git',['-c','core.autocrlf=false','archive',pin,'src/layaAir/flash/utils'],{cwd:engine,maxBuffer:32*1024*1024});cp.execFileSync('tar',['-xf','-','-C',providerSource],{input:archive});
 const exports=['AS3MethodBinding','AS3Coercion','AS3String','AS3Type','AS3Property','AS3Class','AS3Invocation','AS3DeclarationType','FlashTypeMetadata'];const providerEntry=exports.map(n=>'export * from "./src/layaAir/flash/utils/'+n+'";').join('\n');
 const providerBuild=esbuild.buildSync({stdin:{contents:providerEntry,resolveDir:providerSource,loader:'ts'},bundle:true,write:false,format:'cjs',platform:'node',target:'es2020',metafile:true});
 const commonSource='(function(){var module={exports:{}};\n'+providerBuild.outputFiles[0].text+'\nObject.assign(exports,module.exports);})();';
 const utils=path.join(providerSource,'src/layaAir/flash/utils'),declarations=path.join(run,'provider');
 const provider=modern.createProgram(exports.map(n=>path.join(utils,n+'.ts')),{target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,declaration:true,emitDeclarationOnly:true,rootDir:utils,outDir:declarations,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts']});
 const providerErrors=diagnostics(provider);fs.writeFileSync(path.join(run,'provider-diagnostics.json'),JSON.stringify(providerErrors,null,2));assert.deepEqual(providerErrors,[]);assert.equal(provider.emit().emitSkipped,false);
 const names=['PropTween'],qname='com.greensock.core.PropTween';
 const source=read(path.join(evidence,'sources/original/com/greensock/core/PropTween.as')),sources={[qname]:source},classes={[qname]:'lazy'};
 const metadataDocument=json(path.join(evidence,'metadata.json'));
 assert.equal(metadataDocument.captureSha256,sha(path.join(evidence,'flash.json')));
 const rebuilt=JSON.parse(cp.execFileSync(process.env.PYTHON||'python',[path.join(__dirname,'extract-metadata.py'),evidence],{encoding:'utf8'}));assert.deepEqual(rebuilt,metadataDocument);
 const metadata={module:'./AS3MethodBinding',classes:{[qname]:metadataDocument.classes[qname]}};
 assert.equal(metadata.classes[qname].sourceSha256,sha(path.join(evidence,'sources/original/com/greensock/core/PropTween.as')));
 const guards=[];function guard(id,fn,pattern){assert.throws(fn,pattern);guards.push(id);}
 const Native=require(path.join(compiler,'lib/emit/native-callable-classes')).NativeCallableClasses;
 const validate=require(path.join(compiler,'lib/emit/native-class-metadata')).validateNativeClassMetadata;
 guard('self-without-metadata',()=>new Native(source,sources,classes,'./AS3MethodBinding','./AS3MethodBinding',undefined,undefined,'./AS3String'),/authority: PropTween/);
 const child=read(path.join(evidence,'sources/original/probe/SelfChild.as'));
 guard('source-subclass-metadata-held',()=>validate('probe.SelfChild',child,{module:'./AS3MethodBinding',classes:metadataDocument.classes}),/ancestry integration pending/);
 for(const [id,mutate] of [['wrong-source-hash',r=>r.sourceSha256='0'.repeat(64)],['wrong-name',r=>r.metadata.name='impostor::PropTween'],['wrong-field-type',r=>r.instanceTraits.find(x=>x.name==='nextNode').type='Object'],['wrong-final-flag',r=>r.metadata.isFinal=false]]){const wrong=structuredClone(metadata);mutate(wrong.classes[qname]);guard(id,()=>validate(qname,source,wrong),/AS3_CLASS_METADATA_UNSUPPORTED/);}
 for(const [id,replacement] of [['required-self','param7:PropTween'],['undefined-self-default','param7:PropTween = undefined'],['numeric-self-default','param7:PropTween = 0']]){
  const changed=source.replace('param7:PropTween = null',replacement);assert.notEqual(changed,source);const records=structuredClone(metadata);records.classes[qname].sourceSha256=crypto.createHash('sha256').update(changed).digest('hex');
  guard(id,()=>new Native(changed,{[qname]:changed},classes,'./AS3MethodBinding','./AS3MethodBinding',records,undefined,'./AS3String'),/optional null default/);
 }
 let negatives=0;for(const change of [r=>r.pop(),r=>r.reverse(),r=>{r.find(x=>x.id==='actual-undefined').value=['undefined','undefined',true];},r=>{r.find(x=>x.id==='actual-eight-links').events.reverse();}]){const wrong=structuredClone(expected);change(wrong);assert.throws(()=>assert.deepEqual(wrong,expected));negatives++;}
 const reports=[],browser=await chromium.launch({headless:true});try{for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015]){
  const dir=path.join(run,'target-'+target);fs.mkdirSync(dir);const specs=[];
  function add(name,source,isTS=true){let code=source;if(isTS){const r=ts.transpileModule(source,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepEqual(r.diagnostics,[]);code=r.outputText;}fs.writeFileSync(path.join(dir,name+(isTS?'.ts':'.js')),source);specs.push({name,code});}
  add('AS3MethodBinding',commonSource,false);add('AS3String',"exports.as3CoerceString=require('./AS3MethodBinding').as3CoerceString;",false);fs.writeFileSync(path.join(dir,'AS3String.d.ts'),'export * from "../provider/AS3String";');for(const helper of ['bound','classBound','nativeClass','callableClass'])add(helper,read(path.join(compiler,'utils',helper+'.ts')));
  for(const name of names){const source=sources[qname];add(name,emit(parse(name+'.as',source),source,{customVisitors:[],definitionsByNamespace:{'com.greensock.core':names},nativeClassInitialization:{classes},nativeCallableClasses:sources,nativeCallableMethodBindingModule:'./AS3MethodBinding',nativeCallableCoercionModule:'./AS3MethodBinding',nativeCallableStringModule:'./AS3String',nativeCallableMetadata:metadata}));}
  fs.writeFileSync(path.join(dir,'AS3MethodBinding.d.ts'),exports.map(n=>'export * from "../provider/'+n+'";').join('\n'));
  const program=modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts'],experimentalDecorators:true,noEmit:true});const errors=diagnostics(program);fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(errors,null,2));assert.deepEqual(errors,[]);
  const script='{const modules=new Map();const specs='+JSON.stringify(specs)+';for(const spec of specs)modules.set(spec.name,{});for(const spec of specs)new Function("exports","require",spec.code)(modules.get(spec.name),request=>modules.get(request.split("/").pop()));'+read(path.join(__dirname,'driver.js'))+'}';fs.writeFileSync(path.join(dir,'bundle.js'),script);
  const context=vm.createContext({});vm.runInContext(script,context);const node=JSON.parse(JSON.stringify(context.result));fs.writeFileSync(path.join(dir,'node.json'),JSON.stringify(node,null,2));assert.deepEqual(node,expected);assert.equal(context.boundaries.length,13);
  const page=await browser.newPage(),pageErrors=[];page.on('pageerror',e=>pageErrors.push(String(e)));await page.addScriptTag({content:script});const web=await page.evaluate(()=>globalThis.result);fs.writeFileSync(path.join(dir,'browser.json'),JSON.stringify(web,null,2));assert.deepEqual(web,expected);assert.deepEqual(await page.evaluate(()=>globalThis.boundaries),JSON.parse(JSON.stringify(context.boundaries)));assert.deepEqual(pageErrors,[]);await page.close();reports.push({target,matchedRows:8,runtimeBoundaries:13,node:true,chromium:true,actualDeclarationDiagnostics:0,bundleSHA256:sha(path.join(dir,'bundle.js'))});
 }
 const inputs=[...new Set(Object.keys(providerBuild.metafile.inputs).filter(n=>n!=='<stdin>').map(n=>path.resolve(n)))].map(p=>({path:path.relative(providerSource,p),sha256:sha(p)}));
 const qualified=JSON.parse(cp.execFileSync(process.execPath,[path.join(__dirname,'qualified-run.cjs'),run],{encoding:'utf8',env:process.env,windowsHide:true}));assert.equal(qualified.originalRows,14);
 const imports=JSON.parse(cp.execFileSync(process.execPath,[path.join(__dirname,'import-run.cjs'),run],{encoding:'utf8',env:process.env,windowsHide:true}));assert.equal(imports.originalRows,16);
 const report={imports:{rows:16,report:'imports/report.json',sha256:sha(path.join(run,'imports/report.json'))},qualified:{rows:14,report:'qualified-report.json',sha256:sha(path.join(run,'qualified-report.json'))},ok:true,baseCompiler:'ee89e73b7e1fe703d849d0e9fe17fad00bcc381d',scope:'Authenticated optional self-reference and self-typed fields; no derived metadata or full timing-cycle admission',engineCommit:pin,originalRows:32,matchedRows:8,unselectedOriginalRows:all.filter(x=>!expected.includes(x)).map(x=>x.id),guards,negatives,reports,providerInputs:inputs,compilerInputs:['src/emit/native-class-metadata.ts','lib/emit/native-class-metadata.js','src/emit/emitter.ts','lib/emit/emitter.js','src/emit/native-callable-classes.ts','lib/emit/native-callable-classes.js','tests/native-self-constructors/run.cjs','tests/native-self-constructors/driver.js','tests/native-self-constructors/qualified-run.cjs','tests/native-self-constructors/import-run.cjs','tests/native-self-constructors/extract-metadata.py','src/emit/native-source-type.ts','lib/emit/native-source-type.js','src/parse/parse-types.ts','lib/parse/parse-types.js','src/syntax/node.ts','lib/syntax/node.js'].map(n=>({path:n,sha256:sha(path.join(compiler,n))})),originalReceiptSHA256:expectedReceipt};fs.writeFileSync(path.join(run,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({ok:true,matchedRows:8,guards:guards.length,negatives,run}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
