const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),cp=require('child_process'),crypto=require('crypto'),vm=require('vm');
const compiler=path.resolve(__dirname,'../..'),engine=process.env.LAYA_ENGINE_REPOSITORY||path.resolve(compiler,'../LayaAir-op2');
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),esbuild=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||require.resolve('playwright',{paths:[compiler,engine]}));const parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit'));
const pin='69789c4fa64dec426cf86a0ecd4cccfedf79be6c',read=p=>fs.readFileSync(p,'utf8'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),json=p=>JSON.parse(read(p));
const evidence=path.join(__dirname,'evidence'),receiptPath=path.join(evidence,'provenance.json');
const expectedReceipt='88bf1983f2ab5952fbd6a37f0701117b202f9546849173aa6d3ca3feb9bd9e5f';assert.equal(sha(receiptPath),expectedReceipt);
for(const item of json(receiptPath).files){const rel=item.path.replace(/\\/g,'/'),p=fs.existsSync(path.join(evidence,rel))?path.join(evidence,rel):path.join(evidence,'sources',rel);assert.equal(sha(p),item.sha256,rel);}
const all=json(path.join(evidence,'flash.json')).rows;assert.equal(all.length,32);const expected=all.filter(x=>x.id.startsWith('string-')||x.id.startsWith('optional-'));assert.equal(expected.length,14);
const cache=path.join(compiler,'.cache/native-string-constructors');fs.mkdirSync(cache,{recursive:true});const run=fs.mkdtempSync(path.join(cache,'run-'));console.log('Evidence: '+run);
function diagnostics(program){return modern.getPreEmitDiagnostics(program).map(d=>({code:d.code,file:d.file?.fileName,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));}
(async()=>{
 const providerSource=path.join(run,'engine');fs.mkdirSync(providerSource);const archive=cp.execFileSync('git',['-c','core.autocrlf=false','archive',pin,'src/layaAir/flash/utils'],{cwd:engine,maxBuffer:32*1024*1024});cp.execFileSync('tar',['-xf','-','-C',providerSource],{input:archive});
 const exports=['AS3MethodBinding','AS3Coercion','AS3String','AS3Type','AS3Property'];const providerEntry=exports.map(n=>'export * from "./src/layaAir/flash/utils/'+n+'";').join('\n');
 const providerBuild=esbuild.buildSync({stdin:{contents:providerEntry,resolveDir:providerSource,loader:'ts'},bundle:true,write:false,format:'cjs',platform:'node',target:'es2020',metafile:true});
 const commonSource='(function(){var module={exports:{}};\n'+providerBuild.outputFiles[0].text+'\nObject.assign(exports,module.exports);})();';
 const utils=path.join(providerSource,'src/layaAir/flash/utils'),declarations=path.join(run,'provider');
 const provider=modern.createProgram(exports.map(n=>path.join(utils,n+'.ts')),{target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,declaration:true,emitDeclarationOnly:true,rootDir:utils,outDir:declarations,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts']});
 const providerErrors=diagnostics(provider);fs.writeFileSync(path.join(run,'provider-diagnostics.json'),JSON.stringify(providerErrors,null,2));assert.deepEqual(providerErrors,[]);assert.equal(provider.emit().emitSkipped,false);
 const names=['Journal','StringPair','OptionalString'],sources=Object.fromEntries(names.map(n=>['probe.'+n,read(path.join(evidence,'sources/original/probe',n+'.as'))])),classes=Object.fromEntries(Object.keys(sources).map(n=>[n,'lazy']));
 const guards=[];function guard(id,fn,pattern){assert.throws(fn,pattern);guards.push(id);}
 const Native=require(path.join(compiler,'lib/emit/native-callable-classes')).NativeCallableClasses;
 const check=(src,module='./AS3String')=>new Native(src,{'probe.Test':src},{'probe.Test':'lazy'},'./AS3MethodBinding',undefined,undefined,undefined,module);
 for(const type of ['Test','Function','Array','Class'])guard('unsupported-'+type,()=>check('package probe {public class Test {public function Test(x:'+type+'=null){}}}'),/constructor parameter coercion needs common provider authority/);
 for(const module of ['',undefined,'bad\nmodule'])guard('missing-provider-'+String(module),()=>new Native(sources['probe.StringPair'],{'probe.StringPair':sources['probe.StringPair']},{'probe.StringPair':'lazy'},'./AS3MethodBinding',undefined,undefined,undefined,module),/String constructor parameters require/);
 for(const value of ['undefined','123','true','NAME'])guard('unsupported-default-'+value,()=>check('package probe {public class Test {public function Test(x:String='+value+'){}}}'),/String constructor default requires/);
 const prop=read(path.join(evidence,'sources/original/com/greensock/core/PropTween.as'));guard('maintained-PropTween-self-reference',()=>new Native(prop,{'com.greensock.core.PropTween':prop},{'com.greensock.core.PropTween':'lazy'},'./AS3MethodBinding','./AS3MethodBinding',undefined,undefined,'./AS3String'),/authority: PropTween/);
 let negatives=0;for(const change of [r=>r.pop(),r=>r.reverse(),r=>{r.find(x=>x.id==='string-undefined').value=['undefined','undefined'];},r=>{r.find(x=>x.id==='string-hooks-order').events.reverse();}]){const wrong=structuredClone(expected);change(wrong);assert.throws(()=>assert.deepEqual(wrong,expected));negatives++;}
 const reports=[],browser=await chromium.launch({headless:true});try{for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015]){
  const dir=path.join(run,'target-'+target);fs.mkdirSync(dir);const specs=[];
  function add(name,source,isTS=true){let code=source;if(isTS){const r=ts.transpileModule(source,{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepEqual(r.diagnostics,[]);code=r.outputText;}fs.writeFileSync(path.join(dir,name+(isTS?'.ts':'.js')),source);specs.push({name,code});}
  add('AS3MethodBinding',commonSource,false);add('AS3String',"exports.as3CoerceString=require('./AS3MethodBinding').as3CoerceString;",false);fs.writeFileSync(path.join(dir,'AS3String.d.ts'),'export * from "../provider/AS3String";');for(const helper of ['bound','classBound','nativeClass','callableClass'])add(helper,read(path.join(compiler,'utils',helper+'.ts')));
  for(const name of names){const source=sources['probe.'+name];add(name,emit(parse(name+'.as',source),source,{customVisitors:[],definitionsByNamespace:{probe:names},nativeClassInitialization:{classes},nativeCallableClasses:sources,nativeCallableMethodBindingModule:'./AS3MethodBinding',nativeCallableCoercionModule:'./AS3MethodBinding',nativeCallableStringModule:'./AS3String'}));}
  fs.writeFileSync(path.join(dir,'AS3MethodBinding.d.ts'),exports.map(n=>'export * from "../provider/'+n+'";').join('\n'));
  const program=modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),{target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,lib:['lib.es2021.d.ts','lib.dom.d.ts'],experimentalDecorators:true,noEmit:true});const errors=diagnostics(program);fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(errors,null,2));assert.deepEqual(errors,[]);
  const script='{const modules=new Map();const specs='+JSON.stringify(specs)+';for(const spec of specs)modules.set(spec.name,{});for(const spec of specs)new Function("exports","require",spec.code)(modules.get(spec.name),request=>modules.get(request.split("/").pop()));'+read(path.join(__dirname,'driver.js'))+'}';fs.writeFileSync(path.join(dir,'bundle.js'),script);
  const context=vm.createContext({});vm.runInContext(script,context);const node=JSON.parse(JSON.stringify(context.result));fs.writeFileSync(path.join(dir,'node.json'),JSON.stringify(node,null,2));assert.deepEqual(node,expected);
  const page=await browser.newPage(),pageErrors=[];page.on('pageerror',e=>pageErrors.push(String(e)));await page.addScriptTag({content:script});const web=await page.evaluate(()=>globalThis.result);fs.writeFileSync(path.join(dir,'browser.json'),JSON.stringify(web,null,2));assert.deepEqual(web,expected);assert.deepEqual(pageErrors,[]);await page.close();reports.push({target,matchedRows:14,node:true,chromium:true,actualDeclarationDiagnostics:0,bundleSHA256:sha(path.join(dir,'bundle.js'))});
 }
 const inputs=[...new Set(Object.keys(providerBuild.metafile.inputs).filter(n=>n!=='<stdin>').map(n=>path.resolve(n)))].map(p=>({path:path.relative(providerSource,p),sha256:sha(p)}));
 const report={ok:true,scope:'String constructor parameters only; self-reference and full timing cycle remain unadmitted',engineCommit:pin,originalRows:32,matchedRows:14,heldRows:all.filter(x=>!expected.includes(x)).map(x=>x.id),guards,negatives,reports,providerInputs:inputs,compilerInputs:['src/emit/emitter.ts','lib/emit/emitter.js','src/emit/native-callable-classes.ts','lib/emit/native-callable-classes.js','tests/native-string-constructors/run.cjs','tests/native-string-constructors/driver.js'].map(n=>({path:n,sha256:sha(path.join(compiler,n))})),originalReceiptSHA256:expectedReceipt};fs.writeFileSync(path.join(run,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({ok:true,matchedRows:14,guards:guards.length,negatives,run}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
