import '@FLASH@/utils/AS3CanonicalPointReference';
import {Point} from '@FLASH@/geom/Point';
import {Rectangle} from '@FLASH@/geom/Rectangle';
import {as3Is} from '@FLASH@/utils/AS3Type';
import {as3GetProperty} from '@FLASH@/utils/AS3Property';
import {as3CallValue,getAS3FunctionIntrinsic} from '@FLASH@/utils/AS3Invocation';
import {NativeSourceClassModule,createNativeSourceClassLoadingSession} from '@FLASH@/utils/NativeSourceClassLoadingSession';
import {ApplicationDomain} from '@FLASH@/system/ApplicationDomain';
export async function run(module:NativeSourceClassModule){
 const rows:any[]=[],checks:string[]=[],row=(id:string,value:unknown)=>rows.push({id,value});
 const check=(id:string,pass:boolean)=>{if(!pass)throw Error(id);checks.push(id);};
 const session=createNativeSourceClassLoadingSession({resolve:()=>module,maxModules:2});
 const a=await session.load('a',new ApplicationDomain(ApplicationDomain.currentDomain));
 const Subject=a.getDefinition('cases.PointReturns') as any,subject=new Subject(),value=new Point(),other=new Point();
 const failure=(fn:()=>unknown)=>{try{fn();return [];}catch(e:any){return [e.name,e.errorID];}};
 row('identity',subject.echo(value)===value);
 row('nullish',[subject.echo(null)===null,subject.echo(undefined)===null]);
 row('make',[as3Is(subject.make(),Point),subject.make()!==subject.make()]);
 row('static',Subject.staticEcho(value)===value);
 row('object',failure(()=>subject.echo({})));
 row('wrong-reference',failure(()=>subject.echo(new Rectangle())));
 row('class',failure(()=>subject.echo(Point)));
 row('finally-valid',[subject.throughFinally(value)===value,subject.count]);
 row('finally-invalid',[failure(()=>subject.throughFinally({})),subject.count]);
 row('replace-invalid',[subject.replace({},other)===other,subject.count]);
 row('replace-valid',[subject.replace(value,other)===other,subject.count]);
 row('replacement-invalid',[failure(()=>subject.replace(value,{})),subject.count]);
 row('catch-invalid',[failure(()=>subject.catchInvalid({},other)),subject.count]);
 row('nested',subject.nested(value)===value);
 const callback=as3GetProperty(subject,'echo') as Function;
 row('bound',[as3CallValue(getAS3FunctionIntrinsic(callback,'call'),()=>[{},value])===value,as3CallValue(getAS3FunctionIntrinsic(callback,'apply'),()=>[null,[null]])===null]);
 row('arity',[failure(()=>as3CallValue(callback,()=>[])),failure(()=>as3CallValue(callback,()=>[value,other]))]);
 const sibling=await session.load('b',new ApplicationDomain(ApplicationDomain.currentDomain));
 const Sibling=sibling.getDefinition('cases.PointReturns') as any;
 check('separate Classes',Sibling!==Subject);
 check('native reference shared',new Sibling().echo(value)===value);
 check('forged Point rejected',JSON.stringify(failure(()=>subject.echo(Object.create(Point.prototype))))===JSON.stringify(['TypeError',1034]));
 check('proxy Point rejected',JSON.stringify(failure(()=>subject.echo(new Proxy(value,{}))))===JSON.stringify(['TypeError',1034]));
 session.retire();check('retained return',as3CallValue(callback,()=>[value])===value);
 return {rows,checks};
}
