const assert=require('assert/strict'),api=require('../../lib'),fs=require('fs'),Module=require('module');
const {nativeGeneratedDeclarationInputs}=require('../../lib/emit/native-generated-declarations');const {sources,hash}=require('./compile.cjs');
module.exports=config=>{
 const input=nativeGeneratedDeclarationInputs(config.plan,config.plan.scope),guards=[];
 const emit=plan=>api.emitNativeSourceClassModule({...config,plan,emitterOptions:{...config.emitterOptions,nativeReferenceCoercion:{...config.emitterOptions.nativeReferenceCoercion,plan}}});
 for(const classScriptSources of [undefined,['bodycases.Trace'],['bodycases.Trace','bodycases.Base']]){const plan=api.createNativeGeneratedDeclarationPlan({...input,classScriptSources});assert.throws(()=>emit(plan),/script global with class-body initializer requires retry identity authority|script global with static initializer requires retry identity authority/);guards.push('missing explicit Class script selection');}
 for(const statement of ['this.missing = 1;','Trace.holder.value = arguments;']){const source=sources['bodycases.Body'].source.replace('Trace.holder.converter=Body.convert;',statement),plan=api.createNativeGeneratedDeclarationPlan({...input,sources:{...sources,'bodycases.Body':{source,sourceSha256:hash(source)}}});assert.throws(()=>emit(plan),statement.includes("arguments")?/method arguments source Array lowering required/:/class-initializer lexical bindings require separate authority/);guards.push('unsupported class-body lexical binding');}
 const file=require.resolve('../../lib/emit/native-generated-emission'),original=fs.readFileSync(file,'utf8'),changed=original.replace('!classBodyScript && members.some','members.some');assert.notEqual(changed,original);const m=new Module(file,module);m.filename=file;m.paths=module.paths;m._compile(changed,file);const live=require(file),saved=live.NativeGeneratedEmission;try{live.NativeGeneratedEmission=m.exports.NativeGeneratedEmission;assert.throws(()=>emit(config.plan),/script global with class-body initializer requires retry identity authority/);guards.push('mutation: original class-body guard');}finally{live.NativeGeneratedEmission=saved;}
 return guards;
};
