const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),z=require('zlib'),cp=require('child_process');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),root=path.resolve(__dirname,'../..'),engine=path.resolve(process.env.LAYA_ENGINE_REPOSITORY||path.join(root,'../engine'));
const archive=path.join(__dirname,'qualified.json.gz'),pinFile=path.join(__dirname,'qualified-pin.json'),retaining=process.argv[2]==='--retain';let packet,bytes,pin;
const names=['native-generated-class-body-retry','native-generated-class-script-retry','native-generated-reference-constants'];
const records=r=>[...r.compilerInputs,...(r.runs||r.results).flatMap(v=>[...v.inputs,...(v.typecheck?v.typecheck.inputs:v.typechecks.flatMap(c=>c.inputs))])];
if(retaining){
 assert.ok(!fs.existsSync(archive));assert.ok(!fs.existsSync(pinFile));const reports=process.argv.slice(3).map(f=>path.resolve(f));assert.equal(reports.length,3);
 const files=new Map(),add=f=>{f=path.resolve(root,f);if(files.has(f))return;const b=fs.readFileSync(f);files.set(f,{file:f,sha256:hash(b),base64:b.toString('base64')});};
 const tree=dir=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())tree(f);else add(f);}};
 for(const [index,file]of reports.entries()){const r=JSON.parse(fs.readFileSync(file));tree(path.dirname(file));if(index<2){for(const i of records(r)){assert.equal(hash(fs.readFileSync(path.resolve(root,i.file))),i.sha256,i.file);add(i.file);}}else{for(const i of r.providerGraph){const f=path.resolve(engine,i.file);assert.equal(hash(fs.readFileSync(f)),i.sha256);add(f);}add(r.observer.file);}for(const f of ['run.cjs','compile.cjs','guards.cjs','observer.ts']){const p=path.join(root,'tests',names[index],f);if(fs.existsSync(p))add(p);}}
 const oracles=['class-body-retry','script-global-initializer-retry','reference-static-initialization'].map(n=>path.join(engine,'tests/nativeFlashOracle',n));for(const dir of oracles)tree(dir);
 const baselineCommit='940e10fe015683256b823c7f888193f4f7249aca',baselineSource=cp.execFileSync('git',['show',baselineCommit+':src/emit/native-generated-emission.ts'],{cwd:root,encoding:'utf8'});add('.cache/class-body-retry-baseline.json');
 packet={root,engine,reports,oracles,baselineCommit,baselineSource,files:[...files.values()]};bytes=z.gzipSync(JSON.stringify(packet),{level:9});pin={sha256:hash(bytes),bytes:bytes.length,files:files.size};
}else{bytes=fs.readFileSync(archive);pin=JSON.parse(fs.readFileSync(pinFile));packet=JSON.parse(z.gunzipSync(bytes));}
assert.equal(hash(bytes),pin.sha256);assert.equal(bytes.length,pin.bytes);const files=new Map(packet.files.map(i=>[i.file,i]));assert.equal(files.size,pin.files);
const read=f=>{f=path.resolve(packet.root,f);const i=files.get(f);assert.ok(i,f);const b=Buffer.from(i.base64,'base64');assert.equal(hash(b),i.sha256,f);return b;},json=f=>JSON.parse(read(f));for(const f of files.keys())read(f);
const expected=packet.oracles.map(dir=>{const receipt=json(path.join(dir,'evidence/receipt.json'));assert.equal(receipt.status,'passed');assert.equal(receipt.capture.identical,true);assert.equal(receipt.capture.runs,2);for(const [f,h]of Object.entries(receipt.artifacts)){assert.equal(hash(read(path.join(dir,'evidence',f))),h,f);if(f.startsWith('source/'))assert.equal(hash(read(path.join(dir,f))),h);}const a=json(path.join(dir,'evidence/run-1/capture.json'));assert.deepEqual(a,json(path.join(dir,'evidence/run-2/capture.json')));assert.equal(a.state.ready,true);assert.equal(a.state.failure,'');return a.state.observations;});
expected[2]=expected[2].filter(row=>!row.id.startsWith('slotlist-')&&!row.id.startsWith('signal-'));assert.deepEqual(expected.map(r=>r.length),[13,13,22]);
const reports=packet.reports.map(json);
for(const [index,r]of reports.entries()){
 const runs=r.runs||r.results;assert.equal(runs.length,2);
 for(const v of runs){if(index<2){const actual=v.actual||v;assert.deepEqual(actual.node.rows,expected[index]);assert.deepEqual(actual.web,actual.node);for(const c of v.typecheck?[v.typecheck]:v.typechecks)assert.deepEqual(c.diagnostics,[]);}else{assert.deepEqual(v.node,expected[index]);assert.deepEqual(v.web,v.node);}}
 const dir=path.join(packet.root,'tests',names[index]);
 if(index<2){assert.deepEqual(runs.map(v=>v.target),['ES5','ES2015']);for(const i of records(r))assert.equal(hash(read(i.file)),i.sha256,i.file);for(const i of r.runnerInputs||[])assert.equal(hash(read(path.join(dir,i.file))),i.sha256);if(r.runnerSha256)assert.equal(hash(read(path.join(dir,'run.cjs'))),r.runnerSha256);if(r.observerSha256)assert.equal(hash(read(path.join(dir,'observer.ts'))),r.observerSha256);}
 else{assert.deepEqual(r.typecheck.diagnostics,[]);assert.equal(r.rejectionGuards,8);for(const i of r.providerGraph)assert.equal(hash(read(path.resolve(packet.engine,i.file))),i.sha256);assert.equal(hash(read(r.observer.file)),r.observer.sha256);for(const i of r.emitted){assert.equal(hash(read(i.file)),i.outputSha256);assert.equal(hash(read(path.join(packet.oracles[2],'source',i.qname.replaceAll('.','/')+'.as'))),i.sourceSha256);}}
}
for(const [q,s]of Object.entries(reports[0].sources)){assert.equal(hash(s.source),s.sourceSha256);assert.equal(s.source,read(path.join(packet.oracles[0],'source',q.replaceAll('.','/')+'.as')).toString());}
for(const v of reports[0].runs){assert.equal(v.guards.length,6);assert.equal(v.guards.filter(g=>g.startsWith('mutation:')).length,1);assert.deepEqual(v.controls.map(c=>c.name),['missing-body-statement','body-before-fields']);const dir=path.join(path.dirname(packet.reports[0]),v.target);for(const [i,c]of v.controls.entries()){assert.equal(c.node.error,undefined);assert.notDeepEqual(c.node.rows,expected[0]);assert.deepEqual(c.node,c.web);const prefix=i?'order-':'';assert.equal(hash(read(path.join(dir,prefix+'mutation-factory.js'))),c.mutationSha256);assert.equal(hash(read(path.join(dir,prefix+'mutation-bundle.js'))),c.bundleSha256);}}
assert.deepEqual(expected[0].find(r=>r.id==='first-order').value,['base-field','base-body','token-field','private-field','after-field','body-first','body-middle','body-throw']);
const baseline=JSON.parse(read('.cache/class-body-retry-baseline.json').toString('utf16le').replace(/^\uFEFF/,''));assert.equal(baseline.held,true);assert.match(packet.baselineSource,/if\(members.some\(member=>member.kind===K.CLASS_INITIALIZER\)\)/);
if(retaining||process.argv.includes('--check-current'))for(const [f,i]of files)assert.equal(hash(fs.readFileSync(f)),i.sha256,f);
if(retaining){fs.writeFileSync(archive,bytes,{flag:'wx'});fs.writeFileSync(pinFile,JSON.stringify(pin,null,2)+'\n',{flag:'wx'});}
console.log(JSON.stringify({status:'verified',rows:13,targets:2,realms:2,guards:6,compilerMutations:1,runtimeMutations:2,adjacentRows:[13,22],typeErrors:0,archive:pin}));module.exports={packet,reports,read};
