const assert=require('assert/strict'),api=require('../../lib'),fs=require('fs'),Module=require('module');
const {nativeGeneratedDeclarationInputs}=require('../../lib/emit/native-generated-declarations');const {sources,hash}=require('./compile.cjs');
module.exports=config=>{
 const input=nativeGeneratedDeclarationInputs(config.plan,config.plan.scope),guards=[];
 const emit=plan=>api.emitNativeSourceClassModule({...config,plan,emitterOptions:{...config.emitterOptions,nativeVectorTypes:{...config.emitterOptions.nativeVectorTypes,plan},nativeReferenceCoercion:{...config.emitterOptions.nativeReferenceCoercion,plan}}});
 for(const change of [{vectorProviderModule:undefined},{classScriptSources:['vectorconst.Trace']}]){assert.throws(()=>emit(api.createNativeGeneratedDeclarationPlan({...input,...change})),/AS3_.*UNSUPPORTED/);guards.push('missing Vector or Class script authority');}
 for(const source of [sources['vectorconst.Holder'].source.replace('private static const hidden:Vector.<int>=Vector.<int>([17]);','private const hidden:Vector.<int>=Vector.<int>([17]);'),sources['vectorconst.Holder'].source.replace('private static const hidden:Vector.<int>=Vector.<int>([17]);','protected static const hidden:Vector.<int>=Vector.<int>([17]);')]){assert.throws(()=>emit(api.createNativeGeneratedDeclarationPlan({...input,sources:{...sources,'vectorconst.Holder':{source,sourceSha256:hash(source)}}})),/AS3_.*UNSUPPORTED/);guards.push('unqualified Vector constant storage');}
 const file=require.resolve('../../lib/emit/native-generated-traits'),original=fs.readFileSync(file,'utf8'),changed=original.replace('!isStatic && member.kind === nodeKind_1.default.CONST_LIST','(isStatic || member.kind === nodeKind_1.default.CONST_LIST)');assert.notEqual(changed,original);const m=new Module(file,module);m.filename=file;m.paths=module.paths;m._compile(changed,file);const live=require(file),saved=live.NativeGeneratedClassTraits;try{live.NativeGeneratedClassTraits=m.exports.NativeGeneratedClassTraits;assert.throws(()=>emit(config.plan),/Vector static\/constant storage requires separate authority/);guards.push('mutation: original Vector storage guard');}finally{live.NativeGeneratedClassTraits=saved;}
 return guards;
};