// Host observer adapted from CollectionEventsProbe; the four subjects are emitted intact.
const nc=load("nativeClass"),errors=load("AS3SourceError"),properties=load("AS3Property");
const read=name=>nc.readNativeClass(load(name)[name]);
const CollectionEvent=read("CollectionEvent"),PropertyChangeEvent=read("PropertyChangeEvent"),PropertyChangeEventKind=read("PropertyChangeEventKind"),EventReturns=read("EventReturns"),Event=load("AS3CanonicalEventConstruction").Event;
const failure=fn=>{try{fn();return [];}catch(e){return errors.isAS3SourceError(e)?[properties.as3GetProperty(e,"name"),properties.as3GetProperty(e,"errorID")]:[e.name,e.errorID];}};
   let rows=[],c=new CollectionEvent(CollectionEvent.COLLECTION_CHANGE);
   rows.push({id:'collection-defaults',value:[c.type,c.bubbles,c.cancelable,c.kind,c.location,c.oldLocation,c.items.length,c.eventPhase]});
   rows.push({id:'collection-fresh-arrays',value:c.items!==new CollectionEvent('x').items});
   let items=[{id:7}],full=new CollectionEvent('custom',true,true,'add',3,4,items);
   rows.push({id:'collection-fields',value:[full.type,full.bubbles,full.cancelable,full.kind,full.location,full.oldLocation,full.items===items]});
   full.preventDefault();let clone=full.clone();
   rows.push({id:'collection-clone',value:[clone!==full,clone instanceof Event,clone.type,clone.kind,clone.location,clone.oldLocation,clone.items===items,clone.bubbles,clone.cancelable,full.isDefaultPrevented(),clone.isDefaultPrevented()]});
   clone.items.push(9);rows.push({id:'collection-shared-items',value:[full.items.length,full.items[1]]});
   rows.push({id:'collection-format',value:full.toString()});
   let ctor=CollectionEvent,converted=new ctor(7,1,0,12,4.9,-2.9,undefined);
   rows.push({id:'collection-conversion',value:[converted.type,converted.bubbles,converted.cancelable,converted.kind,converted.location,converted.oldLocation,converted.items.length]});
   rows.push({id:'collection-array-rejection',value:failure(function() {new ctor('x',false,false,null,0,0,{});})});
   rows.push({id:'collection-arity',value:[failure(function(){new ctor();}),failure(function(){new ctor('x',false,false,null,0,0,null,8);})]});
   let p=new PropertyChangeEvent(PropertyChangeEvent.PROPERTY_CHANGE);
   rows.push({id:'property-defaults',value:[p.type,p.bubbles,p.cancelable,p.kind,p.property,p.oldValue,p.newValue,p.source,p.eventPhase]});
   let source={id:1},key={id:2},oldValue={id:3},newValue={id:4};
   p=new PropertyChangeEvent('custom',true,true,'delete',key,oldValue,newValue,source);
   rows.push({id:'property-identity',value:[p.kind,p.property===key,p.oldValue===oldValue,p.newValue===newValue,p.source===source]});
   p.preventDefault();let pc=p.clone();
   rows.push({id:'property-clone',value:[pc!==p,pc instanceof Event,pc.type,pc.bubbles,pc.cancelable,pc.kind,pc.property===key,pc.oldValue===oldValue,pc.newValue===newValue,pc.source===source,p.isDefaultPrevented(),pc.isDefaultPrevented()]});
   let update=PropertyChangeEvent.createUpdateEvent(source,key,oldValue,newValue);
   rows.push({id:'property-update',value:[update.type,update.bubbles,update.cancelable,update.kind,update.source===source,update.property===key,update.oldValue===oldValue,update.newValue===newValue]});
   update=PropertyChangeEvent.createUpdateEvent(null,null,null,null);
   rows.push({id:'property-update-null',value:[update.kind,update.source,update.property,update.oldValue,update.newValue]});
   ctor=PropertyChangeEvent;p=new ctor(7,1,0,12,undefined,undefined,undefined,undefined);
   rows.push({id:'property-conversion',value:[p.type,p.bubbles,p.cancelable,p.kind,p.property,p.oldValue,p.newValue,p.source]});
   rows.push({id:'property-arity',value:[failure(function(){new ctor();}),failure(function(){new ctor('x',false,false,null,null,null,null,null,9);})]});
   rows.push({id:'event-kind-constants',value:[PropertyChangeEventKind.UPDATE,PropertyChangeEventKind.DELETE]});
   let returns=new EventReturns(),native=new Event('native');
   rows.push({id:'return-identity',value:[returns.echo(native)===native,returns.echo(full)===full]});
   rows.push({id:'return-null',value:[returns.echo(null)===null,returns.echo(undefined)===null]});
   rows.push({id:'return-invalid',value:[failure(function(){returns.echo({});}),failure(function(){returns.echo(7);})]});
   rows.push({id:'return-static',value:[EventReturns.echoStatic(full)===full,EventReturns.echoStatic(undefined)===null,failure(function(){EventReturns.echoStatic({});})]});
   rows.push({id:'return-finally-override',value:[returns.withFinally(native,full,true)===full,returns.log.length]});
   let finallyFailure=failure(function(){returns.withFinally({},full,true);});
   rows.push({id:'return-finally-invalid',value:[finallyFailure,returns.log.length]});
   rows.push({id:'return-finally-invalid-override',value:[failure(function(){returns.withFinally(native,{},true);}),returns.log.length]});

globalThis.result=rows;
