const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),cp=require('node:child_process'),crypto=require('node:crypto');
const here=__dirname,compiler=path.resolve(here,'../..'),engine=path.resolve(process.env.LAYAAIR_CHECKOUT||path.join(compiler,'../LayaAir-op2'));
const ts=require(path.join(compiler,'node_modules/typescript')),modern=require(path.join(engine,'node_modules/typescript')),{build}=require(path.join(engine,'node_modules/esbuild'));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||require.resolve('playwright',{paths:[compiler,engine]}));
const parse=require(path.join(compiler,'lib/parse')),emit=require(path.join(compiler,'lib/emit')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function evidence(dir,digest,count){const receipt=path.join(dir,'provenance.json');assert.equal(sha(receipt),digest);for(const file of JSON.parse(fs.readFileSync(receipt)).files){const rel=file.path.replace(/\\/g,'/'),p=fs.existsSync(path.join(dir,rel))?path.join(dir,rel):path.join(dir,'sources',rel);assert.equal(sha(p),file.sha256,rel);}const rows=JSON.parse(fs.readFileSync(path.join(dir,'flash.json'))).rows;assert.equal(rows.length,count);assert(rows.every(r=>!r.error));return {source:fs.readFileSync(path.join(dir,'sources/original/Subject.as'),'utf8'),rows,receiptSHA256:digest};}
const groups=[evidence(path.join(here,'../native-array-literals/original-evidence-26-valid'),'f37e64905681459e16c011e10dd8fa7b403749e38b91109ba3718361ebe254d2',26),evidence(path.join(here,'original-evidence'),'6967cb44c88f9c983b90c9a8aaff8b8ddc277ebac0f9eb939dbb909552d3b4a9',10)];
function options(source,extra={}){return {customVisitors:[],definitionsByNamespace:{},nativeClassInitialization:{classes:{Subject:'lazy'}},nativeCallableMethodBindingModule:'./CommonProvider',nativeCallableCoercionModule:'./CommonProvider',nativeCallableClasses:{Subject:source},nativeArrayCreationModule:'./ArrayFactory',...extra};}
function generate(source,extra){return emit(parse('Subject.as',source),source,options(source,extra));}
function exercise(Subject,getCreation,count,allocated){let checked=0;function shape(value){if(Array.isArray(value)){const creation=getCreation(value);if(allocated){if(!creation||creation.kind!=='values'||creation.initialLength!==value.length)throw Error('source array lacks literal creation provenance');checked++;}else if(creation)throw Error('legacy allocation changed');const slots=[];for(let i=0;i<value.length;i++)slots.push({own:Object.prototype.hasOwnProperty.call(value,String(i)),value:shape(value[i])});return {kind:'Array',length:value.length,slots};}return {kind:typeof value,value:value===undefined?'undefined':value};}const rows=Array.from({length:count},(_,index)=>({index,value:shape(new Subject(index).value)}));if(getCreation([]))throw Error('host array adopted');return {rows,checked};}
const simple='package{public class Subject{public var value:Array;public function Subject(){value=[,];}}}';
let guards=0;
for(const module of [null,'',' ',3,'x";bad','x\\bad','x\n','x\u2028','x\u2029']){assert.throws(()=>generate(simple,{nativeArrayCreationModule:module}),/AS3_ARRAY_CREATION_UNSUPPORTED/);guards++;}
for(const extra of [{nativeCallableClasses:undefined},{nativeClassInitialization:undefined},{useNamespaces:true}]){assert.throws(()=>generate(simple,extra),/AS3_ARRAY_CREATION_UNSUPPORTED/);guards++;}
// Vector's element-list node is not source Array allocation. Its nested Array is.
const vector=generate('package{public class Subject{public function Subject(){var v:Vector.<Array>=new <Array>[[1]];}}}');assert.equal((vector.match(/__as3_source_arrayLiteral\(/g)||[]).length,1);guards++;
const lowered=require(path.join(compiler,'lib/emit/native-source-operations')).lowerNativeSourceOperations('authoredFactory([1]);','provider',new Set(['__compilerFactory']),n=>n);assert.match(lowered,/provider\.as3CallValue\(authoredFactory/);guards++;
(async()=>{const outRoot=path.join(compiler,'.cache/native-array-allocation');fs.mkdirSync(outRoot,{recursive:true});const output=fs.mkdtempSync(path.join(outRoot,'run-')),provider=path.join(output,'engine');fs.mkdirSync(provider);const pin='69789c4fa64dec426cf86a0ecd4cccfedf79be6c';const archive=cp.execFileSync('git',['archive','--format=tar',pin,'src/layaAir/flash/utils'],{cwd:engine,maxBuffer:32*1024*1024});cp.execFileSync('tar',['-xf','-','-C',provider],{input:archive});const reports=[];let browser;
try{browser=await chromium.launch({headless:true});for(const target of [ts.ScriptTarget.ES5,ts.ScriptTarget.ES2015])for(let group=0;group<groups.length;group++)for(const allocated of [true,false]){const dir=path.join(output,'target-'+target+'-group-'+group+'-'+allocated);fs.mkdirSync(dir);const {source,rows:expected}=groups[group];
const generated=generate(source,allocated?{}:{nativeArrayCreationModule:undefined});fs.writeFileSync(path.join(dir,'Subject.ts'),generated);
for(const name of ['bound','classBound','nativeClass','callableClass'])fs.copyFileSync(path.join(compiler,'utils',name+'.ts'),path.join(dir,name+'.ts'));
fs.writeFileSync(path.join(dir,'CommonProvider.ts'),['AS3MethodBinding','AS3Coercion'].map(n=>'export * from "../engine/src/layaAir/flash/utils/'+n+'";').join('\n'));
fs.writeFileSync(path.join(dir,'ArrayFactory.ts'),'export * from "../engine/src/layaAir/flash/utils/AS3ArrayCreation";');
fs.writeFileSync(path.join(dir,'entry.js'),'const {Subject}=require("./Subject"),{readNativeClass}=require("./nativeClass"),{getAS3ArrayCreation}=require("./ArrayFactory");exports.result=('+exercise.toString()+')(readNativeClass(Subject),getAS3ArrayCreation,'+expected.length+','+allocated+');');
const flags={target:modern.ScriptTarget.ES2021,module:modern.ModuleKind.CommonJS,strict:true,strictNullChecks:false,skipLibCheck:true,downlevelIteration:true,experimentalDecorators:true,declaration:true,stripInternal:true,emitDeclarationOnly:true,outDir:path.join(dir,'types'),lib:['lib.es2021.d.ts','lib.dom.d.ts']};
const program=modern.createProgram(fs.readdirSync(dir).filter(n=>n.endsWith('.ts')).map(n=>path.join(dir,n)),flags),diagnostics=modern.getPreEmitDiagnostics(program).map(d=>({file:d.file?.fileName,code:d.code,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));fs.writeFileSync(path.join(dir,'diagnostics.json'),JSON.stringify(diagnostics,null,2));assert.deepStrictEqual(diagnostics,[]);assert.equal(program.emit().emitSkipped,false);
// Consume generated declarations against the actual common provider declarations.
const consumer='import {Subject} from "./types/'+path.basename(dir)+'/Subject";import {readNativeClass} from "./types/'+path.basename(dir)+'/nativeClass";import {as3CreateArrayLiteral} from "./types/engine/src/layaAir/flash/utils/AS3ArrayCreation";const item:Subject=new (readNativeClass(Subject))(0);const values:any[]=item.value;const array:unknown[]=as3CreateArrayLiteral(values);const length:number=array.length;';fs.writeFileSync(path.join(dir,'Consumer.ts'),consumer);const consumerDiagnostics=modern.getPreEmitDiagnostics(modern.createProgram([path.join(dir,'Consumer.ts')],{...flags,noEmit:true,emitDeclarationOnly:false})).map(d=>({code:d.code,message:modern.flattenDiagnosticMessageText(d.messageText,'\n')}));assert.deepStrictEqual(consumerDiagnostics,[]);
fs.writeFileSync(path.join(dir,'MissingFactory.ts'),'export const unrelated=1;');
fs.writeFileSync(path.join(dir,'MissingSubject.ts'),generated.replace(/from "\.\/ArrayFactory"/g,'from "./MissingFactory"'));
if(allocated){const errors=modern.getPreEmitDiagnostics(modern.createProgram([path.join(dir,'MissingSubject.ts')],{...flags,noEmit:true,emitDeclarationOnly:false}));assert(errors.some(d=>d.code===2305&&modern.flattenDiagnosticMessageText(d.messageText,' ').includes('as3CreateArrayLiteral')),'missing provider export must fail type checking');}

for(const name of fs.readdirSync(dir).filter(n=>n.endsWith('.ts')&&!['Consumer.ts','MissingFactory.ts','MissingSubject.ts'].includes(n))){const result=ts.transpileModule(fs.readFileSync(path.join(dir,name),'utf8'),{compilerOptions:{target,module:ts.ModuleKind.CommonJS,experimentalDecorators:true},reportDiagnostics:true});assert.deepStrictEqual(result.diagnostics,[]);fs.writeFileSync(path.join(dir,name.replace(/\.ts$/,'.js')),result.outputText);}
const bundles=await Promise.all(['node','browser'].map(platform=>build({entryPoints:[path.join(dir,'entry.js')],bundle:true,platform,format:platform==='node'?'cjs':'iife',globalName:'AllocationProbe',outfile:path.join(dir,platform+'.bundle.js'),metafile:true})));
const node=require(path.join(dir,'node.bundle.js')).result;assert.deepStrictEqual(node.rows,expected);assert.equal(node.checked>0,allocated);
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.addScriptTag({path:path.join(dir,'browser.bundle.js')});const chrome=await page.evaluate(()=>AllocationProbe.result);await page.close();assert.deepStrictEqual(chrome,node);assert.deepStrictEqual(errors,[]);
reports.push({target,group,allocated,rows:node.rows.length,creationChecks:node.checked,nodeMatched:true,chromeMatched:true,diagnostics,consumerDiagnostics,inputs:[...new Set(bundles.flatMap(b=>Object.keys(b.metafile.inputs)))].map(p=>({path:path.relative(output,path.resolve(p)).replace(/\\/g,'/'),sha256:sha(p)}))});}
const report={scope:'Explicit source Array literal creation only; no mutation/storage/splice or source Array call/new admission',engineCommit:pin,originalRows:36,guards,negativeControls:2,receipts:groups.map(g=>g.receiptSHA256),sourceTargets:['ES5','ES2015'],actualDeclarationTarget:'ES2021',reports,compilerSHA256:sha(path.join(compiler,'src/emit/emitter.ts'))};
// Baseline/legacy mode is a negative control for required provenance; corrupt own-slot evidence is independently detected.
assert.throws(()=>exercise(class{constructor(){this.value=[];}},()=>undefined,1,true),/lacks literal/);const bad=JSON.parse(JSON.stringify(groups[0].rows));bad[4].value.slots[0].own=false;assert.throws(()=>assert.deepStrictEqual(bad,groups[0].rows));
fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({ok:true,output,originalRows:36,guards,replays:reports.length}));}finally{if(browser)await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
