import {ApplicationDomain} from '@FLASH@/system/ApplicationDomain';
import {createNativeSourceClassLoadingSession} from '@FLASH@/utils/NativeSourceClassLoadingSession';
import {as3GetProperty as get} from '@FLASH@/utils/AS3Property';
import {as3CallValue} from '@FLASH@/utils/AS3Invocation';
import {as3ConstructClass} from '@FLASH@/utils/AS3Class';
import {as3IsSourceErrorInstance} from '@FLASH@/errors/AS3SourceError';
export async function run(module){
 const root=ApplicationDomain.currentDomain,domain=new ApplicationDomain(root),session=createNativeSourceClassLoadingSession({resolve:()=>module,maxModules:2});const loaded=await session.load('emvc',domain);
 const cls=n=>domain.getDefinition(n),make=(n,...args)=>as3ConstructClass(cls(n),args),call=(o,n,...args)=>as3CallValue(get(o,n),()=>args),rows=[],row=(id,value)=>rows.push({id,value});
 const observe=(id,fn)=>{try{row(id,fn());}catch(e){if(!as3IsSourceErrorInstance(e))throw e;row(id,[e.name,e.errorID,e.message]);}};
 row('linked-subjects',domain.getQualifiedDefinitionNames().filter(n=>n.startsWith('org.emvc.')).length);
 const model=make('org.emvc.core.Model'),proxy=make('org.emvc.patterns.proxy.Proxy','one');
 row('model-empty',call(model,'getProxyByName','one')===null);row('model-register',call(model,'registerProxy',proxy)===proxy);
 observe('model-duplicate',()=>call(model,'registerProxy',proxy));observe('model-missing-remove',()=>{call(model,'removeProxy','missing');return true;});
 call(model,'registerProxy',proxy,'alias');call(model,'removeProxy','one');row('model-alias',[call(model,'getProxyByName','one')===null,call(model,'getProxyByName','alias')===proxy]);
 const view=make('org.emvc.core.View'),mediator=make('org.emvc.patterns.mediator.Mediator','one');
 row('view-empty',call(view,'getMediatorByName','one')===null);row('view-register',call(view,'registerMediator',mediator)===mediator);
 observe('view-duplicate',()=>call(view,'registerMediator',mediator));observe('view-missing-remove',()=>{call(view,'removeMediator','missing');return true;});
 const access=make('emvcprobe.ViewAccess');call(access,'replace','changed:');observe('view-shared-write',()=>call(view,'registerMediator',mediator));call(access,'replace','Mediator name registered.');
 call(view,'removeMediator','one');row('view-remove',call(view,'getMediatorByName','one')===null);
 const command=make('org.emvc.patterns.order.ModuleOrderCommand');observe('private-order-message',()=>{call(command,'execute',make('org.emvc.patterns.order.SimpleOrder',3,{}));return true;});
 observe('public-command-message',()=>call(make('org.emvc.patterns.order.SimpleOrderCommand'),'getType'));
 const manager=get(cls('org.emvc.patterns.order.OrderManager'),'inst');row('order-singleton',manager===get(cls('org.emvc.patterns.order.OrderManager'),'inst'));
 observe('order-second-constructor',()=>make('org.emvc.patterns.order.OrderManager'));row('order-register',call(manager,'registerCommand',77,command));observe('order-duplicate',()=>call(manager,'registerCommand',77,command));
 row('order-has',call(manager,'hasCommand',77));call(manager,'removeCommand',77);row('order-remove',call(manager,'hasCommand',77));
 const facade=get(cls('org.emvc.patterns.facade.Facade'),'inst');row('facade-singleton',facade===get(cls('org.emvc.patterns.facade.Facade'),'inst'));
 const entrance=make('org.emvc.core.Entrance','unit');call(entrance,'installModel',model);call(entrance,'installView',view);call(facade,'installEntrance',entrance);row('facade-proxy',call(facade,'getProxy','unit','alias')===proxy);observe('facade-duplicate',()=>{call(facade,'installEntrance',entrance);return true;});
 const sender=get(cls('org.emvc.patterns.communication.MessageSender'),'inst');row('message-singleton',sender===get(cls('org.emvc.patterns.communication.MessageSender'),'inst'));
 const payload={value:7},message=make('org.emvc.patterns.communication.Message','hello',payload);row('message-fields',[get(message,'type'),get(message,'data')===payload,get(message,'bubbles'),get(message,'cancelable')]);row('message-dispatch',call(sender,'sendMessage',message));
 // Module ownership checks are separate from the AIR behavior rows above.
 const checks=[],check=(id,ok)=>{if(!ok)throw Error(id);checks.push(id);};
 const childDomain=new ApplicationDomain(domain),childSession=createNativeSourceClassLoadingSession({resolve:()=>module,maxModules:1}),child=await childSession.load('emvc',childDomain);
 check('all inherited definitions reused',loaded.names.every(n=>child.getDefinition(n)===cls(n)));
 check('inherited definitions not republished',childDomain.getQualifiedDefinitionNames().length===0);
 check('inherited singleton reused',get(child.getDefinition('org.emvc.patterns.order.OrderManager'),'inst')===manager);
 const sibling=await session.load('sibling',new ApplicationDomain(root));
 check('all sibling definitions fresh',loaded.names.every(n=>sibling.getDefinition(n)!==cls(n)));
 check('sibling singleton fresh',get(sibling.getDefinition('org.emvc.patterns.order.OrderManager'),'inst')!==manager);
 const otherView=as3ConstructClass(sibling.getDefinition('org.emvc.core.View'),[]),otherMediator=as3ConstructClass(sibling.getDefinition('org.emvc.patterns.mediator.Mediator'),['one']);
 call(view,'registerMediator',mediator);call(otherView,'registerMediator',otherMediator);
 const duplicate=v=>{try{call(v,'registerMediator',v===view?mediator:otherMediator);}catch(e){if(!as3IsSourceErrorInstance(e))throw e;return e.message;}throw Error('duplicate accepted');};
 call(access,'replace','parent-only:');
 check('parent protected storage mutated',duplicate(view)==='parent-only:Mediator name: one');
 check('sibling protected storage isolated',duplicate(otherView)==='Mediator name registered.Mediator name: one');
 call(as3ConstructClass(child.getDefinition('emvcprobe.ViewAccess'),[]),'replace','child-write:');
 check('inherited protected storage shared',duplicate(view)==='child-write:Mediator name: one');
 childSession.retire();await childSession.whenIdle();
 check('parent survives child retirement',loaded.active&&domain.getDefinition('org.emvc.core.View')===cls('org.emvc.core.View'));
 session.retire();await session.whenIdle();
 check('owned definitions withdrawn',!loaded.active&&!sibling.active&&!domain.hasDefinition('org.emvc.core.View'));
 check('retained instance storage survives retirement',duplicate(view)==='child-write:Mediator name: one');
 return {rows,checks};
}
