const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const api=require('../../lib'),ts=require('typescript'),engine=path.resolve(process.env.LAYA_ENGINE_REPOSITORY||'../LayaAir-op2');
const esbuild=require(path.join(engine,'node_modules/esbuild')),modern=require(path.join(engine,'node_modules/typescript'));
const evidence=path.join(engine,'tests/nativeFlashOracle/file-local-classes');assert.equal(require(path.join(evidence,'verify.cjs')).length,24);
const root=path.resolve('.cache/native-generated-private-declarations');fs.mkdirSync(root,{recursive:true});const out=fs.mkdtempSync(path.join(root,'run-'));
const hash=s=>crypto.createHash('sha256').update(s).digest('hex'),sources={};
for(const file of fs.readdirSync(path.join(evidence,'source'),{recursive:true}).filter(f=>f.endsWith('.as'))){const source=fs.readFileSync(path.join(evidence,'source',file),'utf8');sources[file.replaceAll('\\','.').replaceAll('/','.').slice(0,-3)]={source,sourceSha256:hash(source)};}
const provider=n=>path.join(engine,'src/layaAir/flash/utils',n).replaceAll('\\','/');
const applicationDomain=path.join(engine,'src/layaAir/flash/system/ApplicationDomain').replaceAll('\\','/');
const input={scope:'private-header',sources,providerModule:provider('AS3DeclarationType'),vectorProviderModule:provider('AS3Vector'),scriptGlobalProviderModule:provider('AS3ScriptGlobal'),scriptDomainProvider:{module:'./domain',exportName:'scriptDomain'},inheritScriptClasses:true};
const plan=api.createNativeGeneratedDeclarationPlan(input);assert.equal(plan.bindings.length,5);assert.equal(plan.privateBindings.length,3);
const [a,child,b]=plan.privateBindings;assert.equal(child.base,a.declaration);assert.notEqual(a.declaration,b.declaration);assert.equal(a.declaration.reflectedName,b.declaration.reflectedName);
assert.equal(plan.references.filter(r=>r.kind==='private-declaration').length,12);assert.equal(plan.vectors.length,2);
for(const p of plan.privateBindings){assert.equal(p.declaration.packageQName,null);assert(!('scriptGlobalExport' in p));assert(!plan.bindings.some(x=>x.qname===p.identity));}
const accessor=require('../../lib/emit/native-generated-declarations');assert.equal(accessor.nativeGeneratedDeclarationSource(plan,plan.scope,a.identity,sources['localcases.First'].source).source,sources['localcases.First'].source);
assert.equal(accessor.nativeGeneratedDeclarationNode(plan,child.identity).findChild(require('../../lib/syntax/nodeKind').default.NAME).text,'Child');
let guards=0;const reject=(fn,re)=>{assert.throws(fn,re);guards++;};
reject(()=>api.emitNativeSourceClassModule({plan,target:'ES2015',emitterOptions:{},externalModules:[],loadingSessionModule:'./session'}),/native Class and reference providers/);
const modified=(q,text,extra={})=>({...input,sources:{[q]:{source:text,sourceSha256:hash(text),...extra}}});
reject(()=>api.createNativeGeneratedDeclarationPlan(modified('a.Unit','package a {public class Unit {}} class X extends Y {} class Y extends X {}')),/cyclic file-private/);
reject(()=>api.createNativeGeneratedDeclarationPlan(modified('a.Unit','package a {public class Unit {}} class X extends Missing {}')),/file-private base requires/);
reject(()=>api.createNativeGeneratedDeclarationPlan(modified('a.Unit','package a {public class Unit {}} class X {}',{referenceOnly:true})),/reference-only/);
reject(()=>api.createNativeGeneratedDeclarationPlan(modified('a.Unit','package a {public class Unit {}} interface I {}')),/file-private interface/);
reject(()=>accessor.nativeGeneratedDeclarationSource({...plan},plan.scope,a.identity,sources['localcases.First'].source),/exact planned/);
const planFile=path.join(out,'headers.ts'),domainFile=path.join(out,'domain.ts');fs.writeFileSync(planFile,plan.moduleSource);fs.writeFileSync(domainFile,'import {createAS3ScriptDomain} from '+JSON.stringify(provider('AS3ScriptGlobal'))+';import {ApplicationDomain} from '+JSON.stringify(applicationDomain)+';export const scriptDomain=createAS3ScriptDomain(ApplicationDomain.createIsolatedScope());');
const program=modern.createProgram([planFile,domainFile,...['glsl.d.ts','spine.d.ts'].map(n=>path.join(engine,'src/layaAir/tslibs',n))],{target:modern.ScriptTarget.ES2020,module:modern.ModuleKind.CommonJS,resolveJsonModule:true,esModuleInterop:true,strict:true,strictNullChecks:false,useUnknownInCatchVariables:false,experimentalDecorators:true,noEmit:true,skipLibCheck:true,lib:['lib.es2020.d.ts','lib.dom.d.ts','lib.dom.iterable.d.ts']});
const diagnostics=modern.getPreEmitDiagnostics(program).map(d=>modern.flattenDiagnosticMessageText(d.messageText,'\n'));assert.deepEqual(diagnostics,[]);
async function main(){const {chromium}=require(require.resolve('playwright',{paths:[path.resolve('../op2-html5/game-client-laya'),engine]}));const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});const results=[];
try{for(const target of ['ES5','ES2015']){
const compiled=ts.transpileModule(plan.moduleSource,{compilerOptions:{target:ts.ScriptTarget[target],module:ts.ModuleKind.CommonJS},reportDiagnostics:true});assert.deepEqual(compiled.diagnostics,[]);
const harness='import {ApplicationDomain} from '+JSON.stringify(applicationDomain)+';import * as types from '+JSON.stringify(provider('AS3DeclarationType'))+';import * as vector from '+JSON.stringify(provider('AS3Vector'))+';import * as script from '+JSON.stringify(provider('AS3ScriptGlobal'))+';import {as3CoerceReference} from '+JSON.stringify(provider('AS3Type'))+';\n'+
'function load(){const domain=script.createAS3ScriptDomain(ApplicationDomain.createIsolatedScope());const exports:any={};const external:any={'+JSON.stringify(input.providerModule)+':types,'+JSON.stringify(input.vectorProviderModule)+':vector,'+JSON.stringify(input.scriptGlobalProviderModule)+':script,"./domain":{scriptDomain:domain}};const require=(name:string)=>external[name];'+compiled.outputText+';return {headers:exports,domain};}\n'+
'export function run(){const one=load(),two=load(),a=one.headers.'+a.tokenExport+',b=one.headers.'+b.tokenExport+',child=one.headers.'+child.tokenExport+';const rows=[types.isAS3DeclarationType(a),a!==b,a.name==="::Helper"&&b.name==="::Helper",types.getAS3DeclarationTypeChain(child).length===2&&types.getAS3DeclarationTypeChain(child)[0]===a&&types.getAS3DeclarationTypeChain(child)[1]===child,a!==two.headers.'+a.tokenExport+',as3CoerceReference(undefined,a)===null,as3CoerceReference(null,a)===null,["Helper","::Helper","localcases.Helper"].every(n=>!script.selectAS3ScriptDomainClass(one.domain,n)),!("Helper" in one.headers)];let rejected=false;try{as3CoerceReference({},a);}catch(e){rejected=true;}rows.push(rejected);if(rows.some(x=>x!==true))throw Error(JSON.stringify(rows));return rows.length;}';
const entry=path.join(out,target+'.ts');fs.writeFileSync(entry,harness);
const nodeFile=path.join(out,target+'.cjs');esbuild.buildSync({entryPoints:[entry],outfile:nodeFile,bundle:true,platform:'node',format:'cjs',target:'es2020'});const checks=require(nodeFile).run();
const bundled=esbuild.buildSync({stdin:{contents:harness+';globalThis["privateResult"]=run();',resolveDir:out,loader:'ts'},write:false,bundle:true,platform:'browser',format:'iife',target:'es2020'}).outputFiles[0].text;
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.route('http://private-header.test/**',route=>route.fulfill({status:200,contentType:route.request().url().endsWith('.js')?'application/javascript':'text/html',headers:{'Content-Security-Policy':"default-src 'none'; script-src 'self'"},body:route.request().url().endsWith('.js')?bundled:'<script src="/case.js"></script>'}));await page.goto('http://private-header.test/');await page.waitForFunction(()=>globalThis.privateResult!==undefined);assert.equal(await page.evaluate(()=>globalThis.privateResult),checks);assert.deepEqual(errors,[]);await page.close();results.push({target,checks,typeErrors:diagnostics.length});
}}finally{await browser.close();}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({qualification:'Generated private declaration headers only; no helper implementation or full Flash replay',guards,results,sourceHashes:plan.sourceHashes},null,2)+'\n');console.log(JSON.stringify({out,guards,results}));}main().catch(e=>{console.error(e);process.exitCode=1;});
