#!/usr/bin/env python3
"""Generate the shared lowercase table from the retained exhaustive AIR scan."""
import argparse
import hashlib
import json
from pathlib import Path

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('--fixture', type=Path, required=True)
p.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'src/hardened-runtime/internal/AS3CaseTable.ts')
p.add_argument('--check', action='store_true')
a = p.parse_args()
golden = a.fixture / 'native-air.json'
data = json.loads(golden.read_text())
sha = lambda path: hashlib.sha256(path.read_bytes()).hexdigest()
if sha(a.fixture / 'StringCaseScan.as') != data['sourceSha256']:
    raise ValueError('Native case scan source has changed')
capture = data['capture']
if capture['runtime']['playerType'] != 'Desktop' or capture['state'].get('ready') is not True:
    raise ValueError('An actual completed native AIR capture is required')
observations = capture['state']['observations']
if len(observations) != 1 or observations[0]['id'] != 'bmp-lowercase':
    raise ValueError('Expected the exhaustive BMP scan')
rows = observations[0]['changes']
previous = -1
lines = []
for row in rows:
    source, target = row['from'], row['to']
    if type(source) is not int or not previous < source < 65536 or not isinstance(target, list) or len(target) != 1 \
            or type(target[0]) is not int or not 0 <= target[0] < 65536 or source == target[0]:
        raise ValueError('Case mapping is not a canonical single-unit native change')
    previous = source
    lines.append(f'    0x{source:04x}: 0x{target[0]:04x},')
text = '\n'.join([
    '// Generated by tools/create-native-case-table.py; do not hand-edit.',
    '// Retained exhaustive AIR evidence SHA256: ' + sha(golden),
    '// Capture SHA256: ' + data['captureSha256'],
    'export const AS3_LOWERCASE_BMP: Readonly<Record<number, number>> = Object.freeze({',
    *lines, '});', '',
])
if a.check:
    if a.output.read_text() != text:
        raise SystemExit('Native lowercase table has drifted')
else:
    a.output.write_text(text)
print(f'{len(rows)} native lowercase mappings')
