const fs=require('fs'),path=require('path'),assert=require('assert/strict'),z=require('zlib'),c=require('crypto');
const hash=b=>c.createHash('sha256').update(b).digest('hex');
const engine=path.resolve(process.env.LAYA_ENGINE_REPOSITORY||'../LayaAir-op2');
const expected=require(path.join(engine,'tests/nativeFlashOracle/vector-conversion/verify.cjs'));
const bytes=fs.readFileSync(path.join(__dirname,'runtime.json.gz'));
assert.equal(hash(bytes),require('./runtime-pin.json').sha256);
const report=JSON.parse(z.gunzipSync(bytes));
assert.equal(report.combined,true);assert.equal(report.emitted.length,1);
const emitted=report.emitted[0];
assert.equal(emitted.source,fs.readFileSync(path.join(engine,'tests/nativeFlashOracle/vector-conversion/source/conversion/Consumer.as'),'utf8'));
assert.equal(hash(emitted.source),emitted.sourceSha256);assert.equal(hash(emitted.output),emitted.outputSha256);
assert.equal(hash(fs.readFileSync(path.join(__dirname,'run.cjs'),'utf8').replace(/\r\n/g,'\n')),report.runnerSha256);
assert.equal(hash(fs.readFileSync(path.join(__dirname,'runtime-driver.js'),'utf8').replace(/\r\n/g,'\n')),report.observer.sha256);
assert.deepEqual(report.results.map(r=>r.target),[1,2]);
for(const result of report.results)assert.deepEqual(result.web,expected);
assert.equal(report.rejectionGuards,4);assert.equal(report.runtimeGuards,3);assert.equal(report.comparisonNegativeControls,3);
assert.deepEqual(report.typecheck.diagnostics,[]);
assert.equal(report.inlineHold.source,fs.readFileSync(path.join(engine,'tests/nativeFlashOracle/vector-conversion-inline/source/conversion/Consumer.as'),'utf8'));
assert.equal(hash(report.inlineHold.source),report.inlineHold.sourceSha256);
assert.equal(report.inlineHold.message,'anonymous callable requires wildcard parameters');
console.log(JSON.stringify({status:'passed',rows:89,targets:2,runtime:'Chromium with Laya',rejectionGuards:4,runtimeGuards:3}));
