const Flags=load('nativeClass').readNativeClass(load('Flags').Flags);
const rows=[];
rows.push({id:'early',value:Flags.early});rows.push({id:'after',value:Flags.after});
rows.push({id:'order',value:Flags.log});rows.push({id:'read',value:Flags.read()});
const Child=load('nativeClass').readNativeClass(load('Child').Child);
rows.push({id:'inherited',value:Child.inherited()});rows.push({id:'changed',value:Flags.change(false)});
rows.push({id:'child-after',value:Child.inherited()});rows.push({id:'child-mutation',value:Child.mutate(true)});
rows.push({id:'base-after',value:Flags.read()});new Child();rows.push({id:'construction',value:Flags.read()});
const Grand=load('nativeClass').readNativeClass(load('Grand').Grand);
const Leaf=load('nativeClass').readNativeClass(load('Leaf').Leaf);
const Sibling=load('nativeClass').readNativeClass(load('Sibling').Sibling);
  rows.push({id:"grand",value:Grand.deepRead()});
  rows.push({id:"leaf",value:Leaf.leafRead()});
  rows.push({id:"leaf-write",value:Leaf.leafWrite(false)});
  rows.push({id:"grand-after-leaf",value:Grand.deepRead()});
  rows.push({id:"base-after-leaf",value:Flags.read()});
  rows.push({id:"child-after-leaf",value:Child.inherited()});
  rows.push({id:"sibling-after-leaf",value:Sibling.siblingRead()});
  rows.push({id:"sibling-write",value:Sibling.siblingWrite(true)});
  rows.push({id:"leaf-after-sibling",value:Leaf.leafRead()});
  rows.push({id:"grand-write",value:Grand.deepWrite(false)});
  const leaf=new Leaf();
  rows.push({id:"leaf-instance",value:leaf.leafInstanceRead()});
  rows.push({id:"leaf-instance-write",value:leaf.leafInstanceWrite(true)});
  rows.push({id:"grand-instance",value:leaf.instanceRead()});
  rows.push({id:"grand-instance-write",value:leaf.instanceWrite(false)});
  rows.push({id:"final-base",value:Flags.read()});
  rows.push({id:"final-leaf",value:Leaf.leafRead()});

// A fresh declaration domain must not share mutable protected static slots.
const fresh=createDomainLoader();
const OtherFlags=fresh('nativeClass').readNativeClass(fresh('Flags').Flags);
const OtherLeaf=fresh('nativeClass').readNativeClass(fresh('Leaf').Leaf);
if(OtherFlags===Flags||OtherLeaf===Leaf)throw Error('domain Class identity leaked');
const original=JSON.stringify(Flags.read());
OtherLeaf.leafWrite(true);
if(JSON.stringify(Flags.read())!==original)throw Error('cross-domain ancestor write');
Leaf.leafWrite(false);
if(OtherLeaf.leafRead()[0]!==true)throw Error('cross-domain reverse write');
globalThis.result=rows;
